// home-lang.js — the homepage's UI strings in English, 中文 and Bahasa Malaysia.
// English values copy the authored HTML exactly (so re-applying English never
// changes the page). Nodes carry data-i18n / data-i18n-html / data-i18n-ph /
// data-i18n-aria pointing at keys below; home.js applies them, and reviews.js
// reads its own dynamic strings (rv_*) through pick() for the current language.
//
// The baker reviews these phrasings — treat names stay recognisable across
// languages, and the tone is warm and simple for a small pet-treat business.

const en = {
  title: "Munchies Furkidz — Handmade Dehydrated Pet Treats",

  // Nav + language switch
  navStory: "OUR STORY",
  navTreats: "OUR TREATS",
  navOrder: "HOW TO ORDER",
  navPostage: "POSTAGE",
  navReviews: "REVIEWS",
  navContact: "CONTACT",

  // Hero
  heroKicker: "HOMEMADE FOR DOGS & CATS · SINCE 2021",
  heroScript: "Every pet deserves fresh treats. ♡",
  heroCopy: "Small-batch treats made with quality ingredients — no preservatives, no shortcuts. After a little break, we're back with a fresh relaunch batch of jerky, biscuits and chewy rolls, posted to you nationwide.",
  ctaOrder: "ORDER ONLINE",
  ctaTreats: "SEE OUR TREATS",

  // Our story
  storyTitle: "OUR STORY — WE'RE BACK!",
  story1: "Munchies Furkidz started in <strong>2021</strong> with a simple goal — making homemade treats that our furkids can enjoy. After a little break while I studied, I'm excited to continue this journey: <strong>new batches, new treats, and the same love</strong>.",
  story2: "Thank you to everyone who supported us before — and welcome to everyone joining us for the first time. 🐶🐱",
  storyQuote: '"Every Pet Deserves Fresh Treats." 🐾',
  storyCaption: "Some memories from the journey so far — stay tuned for our relaunch batch.",

  // Our treats
  bakesTitle: "OUR TREATS",
  bakesSub: "Slow-made in small batches — no preservatives, no added sugar. Real ingredients, clearly labelled, for dogs and cats.",
  p1Name: "CHICKEN JERKY",
  p1Size: "50/100g pack",
  p1Desc: "Just chicken breast, sliced thin and dried slowly until it's crisp. One ingredient: chicken breast. Nothing added. Light, wide strips that snap cleanly in your hand.",
  p2Name: "DUCK JERKY",
  p2Size: "50/100g pack",
  p2Desc: "Duck fillet, dried slowly into dark, rich strips. One ingredient: duck fillet. Nothing added. Firm and crisp, with a deep flavour that stands out.",
  p3Name: "PORK JERKY",
  porkTag: "PORK",
  p3Size: "50/100g pack",
  p3Desc: "Pork loin, sliced thin and dried slowly. A good choice for pets who can't have chicken or duck. One ingredient: pork. Nothing added. Light golden strips that break easily into smaller pieces.",
  p4Name: "CHICKEN POTATO PUFF",
  p4Size: "80g pack",
  p4Desc: "Chicken jerky with sweet potato piped on top, dried until crisp. Chicken, sweet potato and rolled oats. Nothing else. Golden swirls down every strip — crunchy the whole way through.",
  p5Name: "CARROT CHICKEN BISCUIT",
  p5Size: "80g pack",
  p5Desc: "70% Chicken and 20% carrot, made into little dinosaur biscuits. Chicken, carrot, oats and egg. Nothing else. Deep gold and crunchy.",
  p6Name: "APPLE CHICKEN ROLL",
  p6Size: "50g pack",
  p6Desc: "Chicken wrapped around sliced apple then slow dried until crisp. Chicken and apple. Nothing else. Little donut that crunch and break apart easily.",
  p7Name: "PEAR CHICKEN ROLL",
  p7Size: "50g pack",
  p7Desc: "Chicken wrapped around sliced pear, and dried until crisp. Chicken and pear. Nothing else. Little donut that crunch and break apart easily.",
  p8Name: "OKRA CHICKEN ROLL",
  p8Size: "50g pack",
  p8Desc: "Chicken wrapped around the lady's finger, then dried until crisp. Chicken and okra. Crunchy sticks that are inseparable.",
  p9Name: "CHINESE YAM CHICKEN",
  p9Size: "80g pack",
  p9Desc: "Chicken blended with Chinese yam, piped into little round coins. Chicken and Chinese yam (山药). Nothing else. Neat round discs that crunch straight through.",
  p10Name: "EGG YOLK MELTS",
  p10Tag: "OUT OF STOCK",
  p10Size: "40g pack",
  p10Desc: "Egg yolk and goat's milk, dried into small drops. Egg yolk and goat-milk powder. Nothing else. Light and crisp, and small enough to break in half for training.",
  allergenNote: "Every pack is clearly labelled with its meat, so you can pick the right treat for your pet — always check with your vet if your furkid has allergies.",

  // Notice boxes
  n1Title: "PRE-ORDER ONLY",
  n1Line: "Orders close at <strong>6:00PM</strong><br>the day before your posting day.",
  n1Small: "Each batch is made fresh after you order — quantities are limited.",
  n2Title: "MADE WITH LOVE ♡",
  n2Line: "Slow-made in small batches and posted to you nationwide.",
  n2Em: "Healthy snacks, happy furkids! 🐾",

  // How to order
  oTitle: "HOW TO ORDER",
  oSub: "Simple, easy and confirmed over WhatsApp.",
  s1t: "PICK POSTING DAY",
  s1d: "Mon / Wed / Fri",
  s2t: "CHOOSE YOUR TREATS",
  s2d: "Select your favourites",
  s3t: "SET YOUR QUANTITY",
  s3d: "Pouches & packs",
  s4t: "ADD YOUR ADDRESS",
  s4d: "Posting nationwide",
  s5t: "CONFIRM & PAY",
  s5d: "WhatsApp + TNG ♡",

  // Postage
  postTitle: "POSTAGE",
  postBoxTitle: "POST — NATIONWIDE",
  postDays: "MONDAY / WEDNESDAY / FRIDAY",
  postFee: "Orders are packed on your chosen day and posted to you. A flat postage fee is added per order and confirmed with you on WhatsApp.",
  waBoxTitle: "WHATSAPP ORDERS",
  waBoxLine: "Prefer to order directly? Message us on WhatsApp — we'll put your order together and confirm everything with you.",

  // Reviews
  rvTitle: "WHAT CUSTOMERS SAY",
  rvSub: "Real words from happy furkids (and their humans) — reviews are welcome in English, Mandarin (中文) or Bahasa Malaysia.",
  rvFormTitle: "LEAVE A REVIEW",
  rvNote: "Did your pet try a Munchies Furkidz treat? Tell us how it went.",
  nameLabel: "Your name",
  namePh: "e.g. Aisyah",
  ratingLabel: "Your rating",
  rvStarsAria: "Star rating, 1 to 5",
  rvStar1: "1 star",
  rvStar2: "2 stars",
  rvStar3: "3 stars",
  rvStar4: "4 stars",
  rvStar5: "5 stars",
  msgLabel: "Your review",
  msgPh: "Which treat did your pet try? What did they think?",
  msgNote: "Write in whichever language you are comfortable with — English, Mandarin or Bahasa Malaysia.",
  langLabel: "Review language",
  photoLabel: "Add a photo (optional)",
  photoTake: "Take photo",
  photoChoose: "Choose photo",
  rvPhotoAlt: "Your photo",
  rvSubmit: "SEND REVIEW",
  rvSending: "Sending…",
  rvErrFields: "Please add your name, a star rating (1–5) and a short review (up to 400 characters).",
  rvTooBig: "That photo is too large — please choose a picture under 25 MB.",
  rvErrSend: "Something went wrong sending your review. Please check your connection and try again.",
  rvEmpty: "No reviews yet — be the first!",
  rvPrevAria: "Previous review",
  rvNextAria: "Next review",
  rvThanksMain: "Thank you — your review and photo reached us. Every review is read personally and appears on this page once it is approved, usually within a day or two.",
  rvThanksHonest: "Honest reviews help other customers choose well — thank you for sharing it.",

  // Footer + developer line
  fTag: "Homemade dehydrated treats for dogs &amp; cats.<br>Small Batch. Big Love. 🐾",
  fWhatsappTitle: "WHATSAPP / ORDER",
  fWaSmall: "Ordering via our store page is fastest.",
  fFollowTitle: "FOLLOW US",
  devBy: "Website by",
  devWa: "WhatsApp the developer",
};

const zh = {
  title: "Munchies Furkidz — 手工脱水宠物零食",

  navStory: "我们的故事",
  navTreats: "我们的零食",
  navOrder: "如何订购",
  navPostage: "邮寄说明",
  navReviews: "顾客评价",
  navContact: "联系我们",

  heroKicker: "狗狗与猫猫的手作零食 · 始于 2021",
  heroScript: "每只毛孩都值得吃到新鲜的零食。♡",
  heroCopy: "精选优质食材、小批量手作——没有防腐剂，没有捷径。小休一阵后，我们带着全新一批肉干、饼干和肉卷重新出发，全马邮寄到您家。",
  ctaOrder: "立即下单",
  ctaTreats: "看看我们的零食",

  storyTitle: "我们的故事 —— 我们回来了！",
  story1: "Munchies Furkidz 始于 <strong>2021 年</strong>，目标很简单——为我们的毛孩亲手制作零食。求学途中暂停一阵后，我很高兴能继续这段旅程：<strong>新的批次、新的零食，还有一样满满的爱</strong>。",
  story2: "感谢从前支持过我们的每一位——也欢迎第一次认识我们的新朋友。🐶🐱",
  storyQuote: "「每只毛孩都值得新鲜美味的零食。」 🐾",
  storyCaption: "这一路上的一些回忆——敬请期待我们的新批次。",

  bakesTitle: "我们的零食",
  bakesSub: "小批量慢工细作——不加防腐剂、不加糖。真材实料、标示清楚，狗狗和猫猫都能安心享用。",
  p1Name: "鸡肉肉干",
  p1Size: "50/100g 包",
  p1Desc: "只用鸡胸肉，切成薄片慢慢烘干至酥脆。成分只有鸡胸肉，无添加。轻薄宽条，一掰就断。",
  p2Name: "鸭肉肉干",
  p2Size: "50/100g 包",
  p2Desc: "鸭柳慢火烘干，变成深色浓郁的肉条。成分只有鸭柳，无添加。扎实酥脆，味道特别醇厚。",
  p3Name: "猪肉肉干",
  porkTag: "猪肉",
  p3Size: "50/100g 包",
  p3Desc: "猪里肌切成薄片慢火烘干。适合不能吃鸡肉或鸭肉的毛孩。成分只有猪肉，无添加。金黄薄条，轻轻一掰就分成小块。",
  p4Name: "鸡肉薯泥泡芙",
  p4Size: "80g 包",
  p4Desc: "鸡肉肉干上挤上红薯，烘干至酥脆。成分只有鸡肉、红薯和燕麦。每条都有金黄旋纹——从头到尾都酥脆。",
  p5Name: "胡萝卜鸡肉饼干",
  p5Size: "80g 包",
  p5Desc: "70% 鸡肉加 20% 胡萝卜，做成小恐龙造型饼干。成分只有鸡肉、胡萝卜、燕麦和鸡蛋。深金黄色，酥脆可口。",
  p6Name: "苹果鸡肉卷",
  p6Size: "50g 包",
  p6Desc: "鸡肉卷上苹果片，慢火烘干至酥脆。成分只有鸡肉和苹果。小巧甜甜圈，一咬就碎。",
  p7Name: "梨子鸡肉卷",
  p7Size: "50g 包",
  p7Desc: "鸡肉卷上梨子片，烘干至酥脆。成分只有鸡肉和梨子。小巧甜甜圈，一咬就碎。",
  p8Name: "秋葵鸡肉卷",
  p8Size: "50g 包",
  p8Desc: "鸡肉卷上羊角豆，烘干至酥脆。成分只有鸡肉和秋葵。脆条紧紧相连，分不开。",
  p9Name: "山药鸡肉条",
  p9Size: "80g 包",
  p9Desc: "鸡肉拌入山药，挤成小圆饼。成分只有鸡肉和山药。圆圆一片，一口咬下酥到底。",
  p10Name: "蛋黄溶豆",
  p10Tag: "暂时缺货",
  p10Size: "40g 包",
  p10Desc: "蛋黄和羊奶烘干成小溶豆。成分只有蛋黄和羊奶粉。轻盈酥脆，小小一颗，训练时还能掰成两半。",
  allergenNote: "每一包都清楚标示肉类，让您能为毛孩选对零食——如果毛孩有过敏，请务必先咨询兽医。",

  n1Title: "仅限预订",
  n1Line: "请在发货日前一天的<br>晚上 <strong>6:00PM</strong> 前完成下单。",
  n1Small: "每个批次都在您下单后才新鲜制作——数量有限。",
  n2Title: "用心制作 ♡",
  n2Line: "小批量慢工细作，全马邮寄到您手上。",
  n2Em: "健康零食，毛孩开心！🐾",

  oTitle: "如何订购",
  oSub: "简单轻松，通过 WhatsApp 确认订单。",
  s1t: "选择发货日",
  s1d: "周一 / 周三 / 周五",
  s2t: "挑选心仪零食",
  s2d: "选择您最喜欢的",
  s3t: "设定数量",
  s3d: "按袋或按包",
  s4t: "填写收件地址",
  s4d: "全马邮寄",
  s5t: "确认并付款",
  s5d: "WhatsApp + TNG ♡",

  postTitle: "邮寄说明",
  postBoxTitle: "邮寄 —— 全马",
  postDays: "周一 / 周三 / 周五",
  postFee: "订单会在您选定的发货日打包并寄出。每笔订单会收取一笔固定邮费，并在 WhatsApp 上与您确认。",
  waBoxTitle: "WHATSAPP 下单",
  waBoxLine: "想直接下单？在 WhatsApp 联系我们即可——我们会帮您搭配好订单，并与您逐项确认。",

  rvTitle: "顾客怎么说",
  rvSub: "来自毛孩爸妈的真实评价——欢迎用英语、中文或马来文书写。",
  rvFormTitle: "留下评价",
  rvNote: "您的毛孩尝过 Munchies Furkidz 零食吗？跟我们说说吧。",
  nameLabel: "您的名字",
  namePh: "例如：Aisyah",
  ratingLabel: "您的评分",
  rvStarsAria: "星级评分，1 至 5",
  rvStar1: "1 星",
  rvStar2: "2 星",
  rvStar3: "3 星",
  rvStar4: "4 星",
  rvStar5: "5 星",
  msgLabel: "您的评价",
  msgPh: "您的毛孩尝的是哪种零食？觉得怎么样？",
  msgNote: "用您觉得舒服的语言书写即可——英语、中文或马来文都可以。",
  langLabel: "评价语言",
  photoLabel: "添加照片（可选）",
  photoTake: "拍照",
  photoChoose: "选择照片",
  rvPhotoAlt: "您的照片",
  rvSubmit: "发送评价",
  rvSending: "发送中…",
  rvErrFields: "请填写您的名字、星级评分（1–5 星）和一段简短评价（400 字以内）。",
  rvTooBig: "照片太大了——请选择 25 MB 以内的图片。",
  rvErrSend: "发送评价时出了点问题，请检查网络后再试一次。",
  rvEmpty: "还没有评价——来当第一个吧！",
  rvPrevAria: "上一条评价",
  rvNextAria: "下一条评价",
  rvThanksMain: "谢谢！您的评价和照片已经送到我们手上。每一则评价我们都会亲自阅读，审核通过后就会出现在这一页，通常一两天内就能看到。",
  rvThanksHonest: "真诚的评价能帮助其他顾客更好地选购——谢谢您的坦诚分享。",

  fTag: "狗狗与猫猫的手工脱水零食。<br>小批量制作 · 满满的爱 🐾",
  fWhatsappTitle: "WHATSAPP / 下单",
  fWaSmall: "通过我们的订购页下单最快。",
  fFollowTitle: "关注我们",
  devBy: "网站制作：",
  devWa: "用 WhatsApp 联系开发者",
};

const ms = {
  title: "Munchies Furkidz — Snek Haiwan Dehidrasi Buatan Tangan",

  navStory: "KISAH KAMI",
  navTreats: "SNEK KAMI",
  navOrder: "CARA MENEMPAH",
  navPostage: "POS",
  navReviews: "ULASAN",
  navContact: "HUBUNGI KAMI",

  heroKicker: "DIBUAT UNTUK ANJING & KUCING · SEJAK 2021",
  heroScript: "Setiap haiwan kesayangan layak mendapat snek yang segar. ♡",
  heroCopy: "Snek kumpulan kecil daripada bahan berkualiti — tanpa bahan pengawet, tanpa jalan pintas. Selepas berehat seketika, kami kembali dengan kelompok baharu jerky, biskut dan gulungan kenyal, dihantar ke seluruh negara.",
  ctaOrder: "TEMPAH DALAM TALIAN",
  ctaTreats: "LIHAT SNEK KAMI",

  storyTitle: "KISAH KAMI — KAMI KEMBALI!",
  story1: "Munchies Furkidz bermula pada <strong>2021</strong> dengan satu matlamat yang mudah — membuat snek buatan sendiri yang dapat dinikmati anak bulu kami. Selepas berehat seketika ketika saya menyambung pelajaran, saya teruja untuk meneruskan perjalanan ini: <strong>kelompok baharu, snek baharu, dan kasih sayang yang sama</strong>.",
  story2: "Terima kasih kepada semua yang menyokong kami sebelum ini — dan selamat datang kepada yang baharu menyertai kami buat pertama kali. 🐶🐱",
  storyQuote: '“Setiap Haiwan Kesayangan Layak Mendapat Snek Segar.” 🐾',
  storyCaption: "Sebahagian kenangan sepanjang perjalanan ini — nantikan kelompok relaunch kami.",

  bakesTitle: "SNEK KAMI",
  bakesSub: "Dibuat perlahan-lahan dalam kumpulan kecil — tanpa bahan pengawet, tanpa gula tambahan. Bahan sebenar, dilabel dengan jelas, untuk anjing dan kucing.",
  p1Name: "JERKY AYAM",
  p1Size: "Pek 50/100g",
  p1Desc: "Hanya dada ayam, dihiris nipis dan dikeringkan perlahan sehingga rangup. Satu bahan sahaja: dada ayam. Tiada tambahan. Jalur ringan dan lebar yang rangup terus di tangan.",
  p2Name: "JERKY ITIK",
  p2Size: "Pek 50/100g",
  p2Desc: "Filet itik, dikeringkan perlahan menjadi jalur gelap yang kaya rasa. Satu bahan sahaja: filet itik. Tiada tambahan. Padat dan rangup, dengan rasa mendalam yang tersendiri.",
  p3Name: "JERKY BABI",
  porkTag: "BABI",
  p3Size: "Pek 50/100g",
  p3Desc: "Daging babi, dihiris nipis dan dikeringkan perlahan. Pilihan baik untuk haiwan yang tidak boleh makan ayam atau itik. Satu bahan sahaja: babi. Tiada tambahan. Jalur kuning keemasan yang mudah dipatahkan kepada kepingan kecil.",
  p4Name: "KEPUK AYAM KENTANG",
  p4Size: "Pek 80g",
  p4Desc: "Jerky ayam dengan keledek di atasnya, dikeringkan sehingga rangup. Ayam, keledek dan oat bergulung. Tiada yang lain. Pusaran keemasan pada setiap jalur — rangup dari hujung ke hujung.",
  p5Name: "BISKUT AYAM LOBAK MERAH",
  p5Size: "Pek 80g",
  p5Desc: "70% ayam dan 20% lobak merah, dibentuk menjadi biskut dinosaur kecil. Ayam, lobak merah, oat dan telur. Tiada yang lain. Kuning keemasan dan rangup.",
  p6Name: "GULUNGAN AYAM EPAL",
  p6Size: "Pek 50g",
  p6Desc: "Ayam digulung dengan hirisan epal, kemudian dikeringkan perlahan sehingga rangup. Ayam dan epal. Tiada yang lain. Donat kecil yang rangup dan mudah berkecai.",
  p7Name: "GULUNGAN AYAM PEAR",
  p7Size: "Pek 50g",
  p7Desc: "Ayam digulung dengan hirisan pear, dan dikeringkan sehingga rangup. Ayam dan pear. Tiada yang lain. Donat kecil yang rangup dan mudah berkecai.",
  p8Name: "GULUNGAN AYAM OKRA",
  p8Size: "Pek 50g",
  p8Desc: "Ayam digulung dengan okra (kacang bendi), kemudian dikeringkan sehingga rangup. Ayam dan okra. Kayu rangup yang tidak dapat dipisahkan.",
  p9Name: "AYAM UBI CINA",
  p9Size: "Pek 80g",
  p9Desc: "Ayam dicampur ubi Cina, dibentuk menjadi bulatan kecil. Ayam dan ubi Cina (山药). Tiada yang lain. Cakera bulat yang rangup sepenuhnya.",
  p10Name: "LEBUR KUNING TELUR",
  p10Tag: "STOK HABIS",
  p10Size: "Pek 40g",
  p10Desc: "Kuning telur dan susu kambing, dikeringkan menjadi titisan kecil. Kuning telur dan serbuk susu kambing. Tiada yang lain. Ringan dan rangup, cukup kecil untuk dipatahkan dua semasa latihan.",
  allergenNote: "Setiap pek dilabel dengan jelas jenis dagingnya, supaya anda boleh memilih snek yang sesuai untuk haiwan anda — sentiasa semak dengan doktor haiwan jika anak bulu anda mempunyai alahan.",

  n1Title: "TEMPOHAN AWAL SAHAJA",
  n1Line: "Tempahan ditutup pada <strong>6:00PM</strong><br>sehari sebelum hari penghantaran anda.",
  n1Small: "Setiap kelompok dibuat segar selepas anda menempah — kuantiti terhad.",
  n2Title: "DIBUAT DENGAN KASIH ♡",
  n2Line: "Dibuat perlahan-lahan dalam kumpulan kecil dan dihantar ke seluruh negara.",
  n2Em: "Snek sihat, anak bulu gembira! 🐾",

  oTitle: "CARA MENEMPAH",
  oSub: "Mudah, ringkas dan disahkan melalui WhatsApp.",
  s1t: "PILIH HARI POS",
  s1d: "Isnin / Rabu / Jumaat",
  s2t: "PILIH SNEK ANDA",
  s2d: "Pilih kegemaran anda",
  s3t: "TETAPKAN KUANTITI",
  s3d: "Pek & bungkus",
  s4t: "ISI ALAMAT ANDA",
  s4d: "Pos seluruh negara",
  s5t: "SAHKAN & BAYAR",
  s5d: "WhatsApp + TNG ♡",

  postTitle: "POS",
  postBoxTitle: "POS — SELURUH NEGARA",
  postDays: "ISNIN / RABU / JUMAAT",
  postFee: "Pesanan dibungkus pada hari pilihan anda dan dihantar kepada anda. Caj pos tetap ditambah bagi setiap pesanan dan disahkan bersama anda melalui WhatsApp.",
  waBoxTitle: "TEMPAHAN WHATSAPP",
  waBoxLine: "Lebih suka menempah terus? Hantar mesej kepada kami di WhatsApp — kami akan sediakan pesanan anda dan sahkan semuanya bersama anda.",

  rvTitle: "APA KATA PELANGGAN",
  rvSub: "Kata-kata sebenar daripada anak bulu yang gembira (dan manusia mereka) — ulasan dialu-alukan dalam Bahasa Inggeris, Mandarin (中文) atau Bahasa Malaysia.",
  rvFormTitle: "TINGGALKAN ULASAN",
  rvNote: "Anak bulu anda sudah cuba snek Munchies Furkidz? Ceritakan pengalaman anda.",
  nameLabel: "Nama anda",
  namePh: "cth. Aisyah",
  ratingLabel: "Penilaian anda",
  rvStarsAria: "Penilaian bintang, 1 hingga 5",
  rvStar1: "1 bintang",
  rvStar2: "2 bintang",
  rvStar3: "3 bintang",
  rvStar4: "4 bintang",
  rvStar5: "5 bintang",
  msgLabel: "Ulasan anda",
  msgPh: "Snek mana yang anak bulu anda cuba? Apa pendapat mereka?",
  msgNote: "Tulis dalam bahasa yang anda selesa — Inggeris, Mandarin atau Bahasa Malaysia.",
  langLabel: "Bahasa ulasan",
  photoLabel: "Tambah foto (pilihan)",
  photoTake: "Ambil gambar",
  photoChoose: "Pilih foto",
  rvPhotoAlt: "Foto anda",
  rvSubmit: "HANTAR ULASAN",
  rvSending: "Menghantar…",
  rvErrFields: "Sila masukkan nama, penilaian bintang (1–5) dan ulasan ringkas (sehingga 400 aksara).",
  rvTooBig: "Foto itu terlalu besar — sila pilih gambar di bawah 25 MB.",
  rvErrSend: "Ada masalah semasa menghantar ulasan. Sila semak sambungan anda dan cuba lagi.",
  rvEmpty: "Belum ada ulasan — jadilah yang pertama!",
  rvPrevAria: "Ulasan sebelumnya",
  rvNextAria: "Ulasan seterusnya",
  rvThanksMain: "Terima kasih — ulasan dan foto anda telah sampai kepada kami. Setiap ulasan dibaca sendiri oleh kami dan akan dipaparkan di sini sebaik sahaja diluluskan, biasanya dalam satu atau dua hari.",
  rvThanksHonest: "Ulasan yang jujur membantu pelanggan lain memilih dengan baik — terima kasih kerana berkongsi.",

  fTag: "Snek haiwan dehidrasi buatan tangan untuk anjing &amp; kucing.<br>Kumpulan Kecil. Kasih Sayang Yang Besar. 🐾",
  fWhatsappTitle: "WHATSAPP / TEMPAH",
  fWaSmall: "Paling cepat dengan menempah melalui halaman kedai kami.",
  fFollowTitle: "IKUTI KAMI",
  devBy: "Laman web oleh",
  devWa: "WhatsApp pembangun",
};

export const HOME = { en, zh, ms };
