// store-lang.js — the store's (store/) customer-facing strings in English,
// 中文 and Bahasa Malaysia. English values copy the authored copy exactly so a
// visit in English is identical to today. Values may contain a %1 placeholder
// (e.g. the cut-off time) that the caller substitutes at render time.
//
// The order data the baker reads (product names, order lines, the WhatsApp
// message) deliberately stays in the products' English names — only what the
// customer sees on the page is localized.

const en = {
  titleWord: "Order",
  referral: "🎁 You were referred — you have a welcome discount on your first order",
  // The scanned-label banner. Its words mirror what the owner states on a label
  // (offerLine in admin/js/codes.js) so the page and the card agree.
  codeOff: "%1 off",
  codeMin: "on %1 and above",
  codeNew: "new customers only",
  codeUntil: "valid until %1",
  codeFrom: "from %1",
  // The "have a code?" box, and the line under the label banner saying what
  // happens to the offer. The note is built in JS (its words carry the basket's
  // own figure), so its strings live here rather than in index.html.
  codeHave: "Have a code? Enter it here.",
  codePh: "e.g. K3X9",
  codeApply: "Apply",
  codeNoteLater: "We'll take this off when we confirm on WhatsApp — the total shown is before the discount.",
  codeNoteAdd: "Add %1 more to use it.",
  codeUnknown: "We don't know that code — check the letters and try again.",
  codeNotePlain: "Saved — that code has no discount on it.",
  deliveryDays: "Posting days",
  orderBy: "Order by",
  beforeVal: "%1 the day before posting",
  madeToOrder: "Made to order · closes %1 the day before",
  sPickDay: "Pick a posting day",
  sWhat: "What would you like?",
  sYourDetails: "Your details",
  yourName: "Your name",
  namePh: "e.g. Aisyah",
  whatsappNo: "WhatsApp number",
  whatsPh: "e.g. 012-345 6789",
  waSub: "We use this to confirm your order and send your payment QR — we'll never spam you.",
  howGet: "How will you get your order?",
  courier: "Post (nationwide)",
  selfCollect: "Collect (local)",
  addressLabel: "Postal address",
  addressPh: "Full address — street, area, town & postcode",
  addressSub: "We post nationwide — your treats are made on the day you pick and posted to this address.",
  noteLabel: "Note (optional)",
  notePh: "Allergies, extras, anything…",
  sTrack: "Track your order",
  trackHint: "Placed an order? Enter the order number from your confirmation (it starts with <strong>#</strong>, e.g. #A3F9C2).",
  trackPh: "e.g. A3F9C2",
  trackBtn: "Track",
  sPolicies: "Policies",

  items: "%1 items",
  oneItem: "1 item",
  placeOrder: "Place order",
  sending: "Sending…",
  soldOut: "Sold out",
  onlyLeft: "Only %1 left",
  noDates: "No upcoming posting days right now — check back soon.",
  noOpenDates: "All upcoming posting days are full right now — check back soon.",
  calChosen: "Your posting day: %1",
  // The two answers to tapping a day this page cannot take an order for. %1 is
  // that day in words, built by fmtDay in this language — so neither sentence may
  // name a weekday of its own. "A green day" is a day she posts and can still
  // take: its number carries the green ring.
  calMiss: "%1 is not a posting day — please pick a green day.",
  // The other one: a day she DOES post, tapped after its window shut. Saying "not
  // a posting day" here would be untrue and would contradict the posting-days
  // line on the card above the grid, so it says what really happened instead.
  calClose: "Orders for %1 have closed — please pick a green day.",
  calPrev: "Previous month",
  calNext: "Next month",

  // Why a product reads "Sold out" on a date it can't be ordered for, and the
  // notes above the menu when a refresh changes the basket. The rule comes from
  // pool.js as data, so the sentence is built here in the visitor's language —
  // including the date, which must not arrive as an English weekday. The advice
  // is separate from the clause because the basket notes quote the clause alone.
  closedFrom: "Only available for posting from %1",
  closedTo: "Only available for posting up to %1",
  closedClose: "Orders close %1 days before the posting day",
  closedCloseAdvice: " — pick a later date",
  // The owner's marked sell days, when the chosen posting day is not one of
  // them. %1 is a weekday list the page joins in this language ("Mon, Wed and
  // Fri"), so the names are built by the page, not here.
  closedWeekday: "Only available on %1",
  closedUnmarked: "Not sold on this day",
  // A product you keep on the shop when it cannot be ordered (the switch in its
  // Availability card): the stamp it wears on a day that is not one of its sell
  // days, and the line naming the next date it CAN be ordered — with how many are
  // left that day, when a daily limit publishes a count. %1 is the date (fmtDay),
  // %2 the count.
  unavailable: "Unavailable",
  nextAvailable: "Next available: %1",
  nextAvailableLeft: "Next available: %1 · %2 left",
  sentenceEnd: ".",
  // Shown where the menu would be when every product is marked off today's
  // posting day — an empty space reads like a broken page.
  noMenuToday: "Nothing is on the menu for this day. Please pick another posting day.",
  fixSoldOut: "%1 just sold out — removed from your order.",
  fixPoolClamp: "%1: only %2 can fit with the rest of your order now — we changed your %3 to %2.",
  fixClamp: "%1: only %2 left now — we changed your %3 to %2.",
  fixClosed: "%1: %2 — we removed it.",

  // How long a customer may still change or cancel this product's order (the
  // owner's stated window — shown, never enforced) and the same window on the
  // order receipt, where it carries the no-refund rule. One day needs its own
  // key so English never reads "1 days".
  cancelNote: "Change or cancel up to %1 days before the posting day.",
  cancelNoteOne: "Change or cancel up to 1 day before the posting day.",
  orderCancelNote: "Change or cancel up to %1 days before the posting day. Payments are not refundable — your order can be moved to another day.",
  orderCancelNoteOne: "Change or cancel up to 1 day before the posting day. Payments are not refundable — your order can be moved to another day.",

  confirmAddWaTitle: "Please add your WhatsApp number.",
  confirmAddWaBody: "We use it to confirm your order and send your payment QR.",
  confirmAddrTitle: "Please add your postal address.",
  confirmAddrBody: "We post nationwide — your treats can't be sent without your full address (street, area, town & postcode).",
  confirmClosedTitle: "That day's orders are closed.",
  confirmClosedBody: "Orders for this day close at %1 the day before — please pick a new posting day.",
  confirmChangedTitle: "Your order changed just now.",
  confirmChangedBody: "Something sold out while you were ordering — we've fixed your cart to match what's left.",
  confirmChangedSub: "Please review your order and tap Place order again.",
  sendingToBakery: "Sending your order…",
  orderRecvTitle: "🎉 Order received!",
  orderRecvBody: "%1 has your order.",
  orderRecvThanksBody: "Thanks %1! %2 has your order.",
  orderRecvLine: "📅 %1 · %2 · RM%3",
  orderRecvSub: "Your order is in — we'll WhatsApp you once we confirm it.",
  failTitle: "We couldn't send your order just now.",
  failBody: "Don't worry — send your order on WhatsApp so it isn't lost.",
  failOpened: "WhatsApp has opened with your order — press Send so it isn't lost.",
  failLink: "📲 Send your order via WhatsApp",
  failRetry: "Please try again in a moment.",

  trackEnter: "Enter your order number to track it.",
  trackUnavailable: "Tracking isn't available right now.",
  trackLooking: "Looking up your order…",
  trackNotFound: "We couldn't find order #%1. Check the number in your confirmation message — it's the 6 characters after the #.",
  orderCode: "Order #%1",
  forCustomer: "For %1",
  trkNew: "New",
  trkConfirmed: "Confirmed",
  trkPaid: "Paid",
  trkBaking: "Preparing",
  trkReady: "Packed",
  trkFinal: "Collected / Posted",
  trackingNo: "Tracking number: %1",
  courierCharge: "Courier charge: %1",
  // The same charge when the courier collects it at the door: COD is the word
  // Malaysians know for a parcel the receiver pays for, so it is kept, with what to
  // do about it spelled out beside it (19 Sep 2026).
  courierCod: "Courier charge: %1 - COD, pay the courier on delivery",
  nextBlockedBasket: "Your basket is for %1. To order for another day, choose it on the calendar above.",

  devBy: "Website by",
  devWa: "WhatsApp the developer",
};

const zh = {
  titleWord: "订购",
  referral: "🎁 经由好友推荐 — 首次下单即可享受专属优惠",
  codeOff: "折扣 %1",
  codeMin: "消费 %1 以上",
  codeNew: "仅限新客户",
  codeUntil: "有效期至 %1",
  codeFrom: "来自 %1",
  codeHave: "有优惠码？在此输入。",
  codePh: "例如 K3X9",
  codeApply: "使用",
  codeNoteLater: "我们会在 WhatsApp 确认订单时为您扣减 —— 目前显示的总额尚未扣除优惠。",
  codeNoteAdd: "再消费 %1 即可使用。",
  codeUnknown: "找不到这个优惠码 —— 请检查字母后再试。",
  codeNotePlain: "已记录 —— 这个优惠码没有折扣。",
  deliveryDays: "发货日",
  orderBy: "下单截止",
  beforeVal: "发货日前一天%1前",
  madeToOrder: "按订单制作 · 发货日前一天%1截单",
  sPickDay: "选择发货日",
  sWhat: "您想要什么？",
  sYourDetails: "您的资料",
  yourName: "您的名字",
  namePh: "例如：Aisyah",
  whatsappNo: "WhatsApp 号码",
  whatsPh: "例如：012-345 6789",
  waSub: "我们会用这个号码确认订单并发送付款二维码，绝不会骚扰您。",
  howGet: "您希望怎样收货？",
  courier: "邮寄（全马）",
  selfCollect: "自取（本地）",
  addressLabel: "邮寄地址",
  addressPh: "完整地址 — 街道、地区、市镇与邮编",
  addressSub: "我们提供全马邮寄——您的零食会在所选发货日制作，并寄往这个地址。",
  noteLabel: "备注（可选）",
  notePh: "过敏原、额外要求、其它…",
  sTrack: "查询订单",
  trackHint: "已经下单了？请输入确认讯息里的订单编号（以 <strong>#</strong> 开头，例如 #A3F9C2）。",
  trackPh: "例如：A3F9C2",
  trackBtn: "查询",
  sPolicies: "条规",

  items: "%1 项",
  oneItem: "1 项",
  placeOrder: "提交订单",
  sending: "发送中…",
  soldOut: "已售完",
  onlyLeft: "仅剩 %1 份",
  noDates: "目前没有可预订的发货日 — 请稍后再来。",
  noOpenDates: "近期发货日均已满 — 请稍后再来。",
  calChosen: "你的发货日：%1",
  calMiss: "%1不是发货日 — 请选择绿色圈起的日期。",
  calClose: "%1的订单已截止 — 请选择绿色圈起的日期。",
  calPrev: "上个月",
  calNext: "下个月",

  closedFrom: "只接受 %1 起的发货日订单",
  closedTo: "只接受 %1 或之前的发货日订单",
  closedClose: "需在发货日前 %1 天下单",
  closedCloseAdvice: " — 请另选较后的日期",
  closedWeekday: "只限 %1 供应",
  closedUnmarked: "这一天没有出售",
  unavailable: "暂无供应",
  nextAvailable: "下次可预订：%1",
  nextAvailableLeft: "下次可预订：%1 · 剩 %2 份",
  sentenceEnd: "。",
  noMenuToday: "这一天没有商品在菜单上，请另选一个发货日。",
  fixSoldOut: "%1 刚刚售完 — 已从你的订单中移除。",
  fixPoolClamp: "%1：现在配合订单其余部分只装得下 %2 份 — 已把你的 %3 改为 %2。",
  fixClamp: "%1：现在只剩 %2 份 — 已把你的 %3 改为 %2。",
  fixClosed: "%1：%2 — 已移除。",

  cancelNote: "可在发货日前 %1 天更改或取消。",
  cancelNoteOne: "可在发货日前 1 天更改或取消。",
  orderCancelNote: "可在发货日前 %1 天更改或取消。款项不退还 — 订单可改期至其他发货日。",
  orderCancelNoteOne: "可在发货日前 1 天更改或取消。款项不退还 — 订单可改期至其他发货日。",

  confirmAddWaTitle: "请填写您的 WhatsApp 号码。",
  confirmAddWaBody: "我们会用它确认订单并发送付款二维码。",
  confirmAddrTitle: "请填写您的邮寄地址。",
  confirmAddrBody: "我们提供全马邮寄——没有完整的邮寄地址（街道、地区、市镇及邮编）就无法寄出您的零食。",
  confirmClosedTitle: "该日的订单已截止。",
  confirmClosedBody: "此日订单需在发货日前一天%1前下单 — 请另选一个发货日。",
  confirmChangedTitle: "您的订单刚刚有变动。",
  confirmChangedBody: "下单期间有零食售完了 — 我们已根据剩余数量更新您的购物车。",
  confirmChangedSub: "请再次确认订单并点击「提交订单」。",
  sendingToBakery: "正在发送您的订单…",
  orderRecvTitle: "🎉 订单已收到！",
  orderRecvBody: "%1 已收到您的订单。",
  orderRecvThanksBody: "谢谢 %1！%2 已收到您的订单。",
  orderRecvLine: "📅 %1 · %2 · RM%3",
  orderRecvSub: "订单已收到 — 确认后我们会通过 WhatsApp 通知您。",
  failTitle: "暂时无法发送您的订单。",
  failBody: "别担心 — 请通过 WhatsApp 发送订单，以免遗漏。",
  failOpened: "WhatsApp 已打开并带上您的订单 — 请按「发送」。",
  failLink: "📲 通过 WhatsApp 发送订单",
  failRetry: "请稍后再试一次。",

  trackEnter: "请输入订单编号查询。",
  trackUnavailable: "现在暂时无法查询。",
  trackLooking: "正在查询您的订单…",
  trackNotFound: "找不到订单 #%1。请检查确认讯息中的编号 — 即 # 号后的 6 个字符。",
  orderCode: "订单 #%1",
  forCustomer: "顾客：%1",
  trkNew: "新订单",
  trkConfirmed: "已确认",
  trkPaid: "已付款",
  trkBaking: "准备中",
  trkReady: "已打包",
  trkFinal: "已取货 / 已寄出",
  trackingNo: "快递单号：%1",
  courierCharge: "快递费：%1",
  courierCod: "快递费：%1 - 货到付款，收货时付给快递员",
  nextBlockedBasket: "你的购物袋是 %1 的。想订另一天，请在上面的日历选择。",

  devBy: "网站制作：",
  devWa: "用 WhatsApp 联系开发者",
};

const ms = {
  titleWord: "Tempahan",
  referral: "🎁 Anda dirujuk — anda ada diskaun sambutan untuk tempahan pertama",
  codeOff: "Diskaun %1",
  codeMin: "pembelian %1 ke atas",
  codeNew: "pelanggan baharu sahaja",
  codeUntil: "sah sehingga %1",
  codeFrom: "daripada %1",
  codeHave: "Ada kod? Masukkan di sini.",
  codePh: "cth. K3X9",
  codeApply: "Guna",
  codeNoteLater: "Kami akan tolak diskaun ini semasa mengesahkan di WhatsApp — jumlah yang dipaparkan belum ditolak diskaun.",
  codeNoteAdd: "Tambah %1 lagi untuk menggunakannya.",
  codeUnknown: "Kami tidak kenal kod itu — semak hurufnya dan cuba lagi.",
  codeNotePlain: "Disimpan — kod itu tiada diskaun.",
  deliveryDays: "Hari pos",
  orderBy: "Tempahan ditutup",
  beforeVal: "%1 sehari sebelum hari pos",
  madeToOrder: "Dibuat mengikut tempahan · tutup %1 sehari sebelum",
  sPickDay: "Pilih hari pos",
  sWhat: "Apa yang anda mahukan?",
  sYourDetails: "Maklumat anda",
  yourName: "Nama anda",
  namePh: "cth. Aisyah",
  whatsappNo: "Nombor WhatsApp",
  whatsPh: "cth. 012-345 6789",
  waSub: "Kami guna nombor ini untuk sahkan tempahan dan hantar QR pembayaran — kami tidak akan spam anda.",
  howGet: "Macam mana anda mahu terima tempahan?",
  courier: "Pos (seluruh negara)",
  selfCollect: "Ambil sendiri (setempat)",
  addressLabel: "Alamat pos",
  addressPh: "Alamat lengkap — jalan, kawasan, bandar & poskod",
  addressSub: "Kami hantar ke seluruh negara — snek anda dibuat pada hari yang anda pilih dan dihantar ke alamat ini.",
  noteLabel: "Nota (pilihan)",
  notePh: "Alahan, tambahan, apa-apa sahaja…",
  sTrack: "Semak tempahan anda",
  trackHint: "Sudah menempah? Masukkan nombor tempahan dari mesej pengesahan (bermula dengan <strong>#</strong>, cth. #A3F9C2).",
  trackPh: "cth. A3F9C2",
  trackBtn: "Semak",
  sPolicies: "Polisi",

  items: "%1 item",
  oneItem: "1 item",
  placeOrder: "Hantar tempahan",
  sending: "Menghantar…",
  soldOut: "Habis",
  onlyLeft: "Tinggal %1 sahaja",
  noDates: "Tiada tarikh pos buat masa ini — sila datang lagi nanti.",
  noOpenDates: "Semua hari pos akan datang penuh buat masa ini — sila datang lagi nanti.",
  calChosen: "Hari pos anda: %1",
  calMiss: "%1 bukan hari pos — sila pilih tarikh bertanda hijau.",
  calClose: "Tempahan untuk %1 telah ditutup — sila pilih tarikh bertanda hijau.",
  calPrev: "Bulan sebelumnya",
  calNext: "Bulan seterusnya",

  closedFrom: "Hanya tersedia untuk pos dari %1",
  closedTo: "Hanya tersedia untuk pos sehingga %1",
  closedClose: "Tempahan ditutup %1 hari sebelum hari pos",
  closedCloseAdvice: " — sila pilih tarikh yang lebih lewat",
  closedWeekday: "Hanya tersedia pada %1",
  closedUnmarked: "Tidak dijual pada hari ini",
  unavailable: "Tidak tersedia",
  nextAvailable: "Seterusnya tersedia: %1",
  nextAvailableLeft: "Seterusnya tersedia: %1 · tinggal %2",
  sentenceEnd: ".",
  noMenuToday: "Tiada apa-apa pada menu untuk hari ini. Sila pilih hari pos yang lain.",
  fixSoldOut: "%1 baru sahaja habis — dikeluarkan dari tempahan anda.",
  fixPoolClamp: "%1: hanya %2 boleh dimuatkan bersama baki tempahan anda — kami telah tukar %3 anda kepada %2.",
  fixClamp: "%1: tinggal %2 sahaja sekarang — kami telah tukar %3 anda kepada %2.",
  fixClosed: "%1: %2 — kami telah keluarkannya.",

  cancelNote: "Tukar atau batal sehingga %1 hari sebelum hari pos.",
  cancelNoteOne: "Tukar atau batal sehingga 1 hari sebelum hari pos.",
  orderCancelNote: "Tukar atau batal sehingga %1 hari sebelum hari pos. Bayaran tidak dikembalikan — tempahan boleh dipindah ke hari lain.",
  orderCancelNoteOne: "Tukar atau batal sehingga 1 hari sebelum hari pos. Bayaran tidak dikembalikan — tempahan boleh dipindah ke hari lain.",

  confirmAddWaTitle: "Sila masukkan nombor WhatsApp anda.",
  confirmAddWaBody: "Kami guna untuk sahkan tempahan dan hantar QR pembayaran anda.",
  confirmAddrTitle: "Sila masukkan alamat pos anda.",
  confirmAddrBody: "Kami hantar ke seluruh negara — snek anda tidak dapat dihantar tanpa alamat lengkap (jalan, kawasan, bandar & poskod).",
  confirmClosedTitle: "Tempahan untuk hari itu sudah ditutup.",
  confirmClosedBody: "Tempahan untuk hari ini ditutup pada %1 sehari sebelum — sila pilih hari pos baharu.",
  confirmChangedTitle: "Tempahan anda baru sahaja berubah.",
  confirmChangedBody: "Ada snek yang habis semasa anda menempah — kami telah kemas kini troli anda mengikut apa yang tinggal.",
  confirmChangedSub: "Sila semak tempahan anda dan tekan Hantar tempahan sekali lagi.",
  sendingToBakery: "Menghantar tempahan anda…",
  orderRecvTitle: "🎉 Tempahan diterima!",
  orderRecvBody: "%1 telah menerima tempahan anda.",
  orderRecvThanksBody: "Terima kasih %1! %2 telah menerima tempahan anda.",
  orderRecvLine: "📅 %1 · %2 · RM%3",
  orderRecvSub: "Tempahan anda telah diterima — kami akan WhatsApp anda sebaik sahaja disahkan.",
  failTitle: "Kami tidak dapat menghantar tempahan anda buat masa ini.",
  failBody: "Jangan risau — hantar tempahan anda melalui WhatsApp supaya ia tidak hilang.",
  failOpened: "WhatsApp telah dibuka dengan tempahan anda — tekan Hantar supaya ia tidak hilang.",
  failLink: "📲 Hantar tempahan anda melalui WhatsApp",
  failRetry: "Sila cuba lagi sebentar lagi.",

  trackEnter: "Masukkan nombor tempahan anda untuk disemak.",
  trackUnavailable: "Semakan tidak tersedia buat masa ini.",
  trackLooking: "Mencari tempahan anda…",
  trackNotFound: "Kami tidak dapat mencari tempahan #%1. Sila semak nombor dalam mesej pengesahan anda — iaitu 6 aksara selepas #.",
  orderCode: "Tempahan #%1",
  forCustomer: "Untuk %1",
  trkNew: "Baharu",
  trkConfirmed: "Disahkan",
  trkPaid: "Dibayar",
  trkBaking: "Sedang disediakan",
  trkReady: "Dibungkus",
  trkFinal: "Telah diambil / Telah dipos",
  trackingNo: "Nombor penjejakan: %1",
  courierCharge: "Caj kurier: %1",
  courierCod: "Caj kurier: %1 - COD, bayar kepada kurier semasa penghantaran",
  nextBlockedBasket: "Bakul anda untuk %1. Untuk hari lain, pilih pada kalendar di atas.",

  devBy: "Laman web oleh",
  devWa: "WhatsApp pembangun",
};

export const STORE = { en, zh, ms };
