// store-lang.js — the store's (store/) customer-facing strings in English,
// 中文 and Bahasa Malaysia. English values copy the authored copy exactly so a
// visit in English is identical to today. Values may contain a %1 placeholder
// (e.g. the cut-off time) that the caller substitutes at render time.
//
// The order data the baker reads (product names, order lines, the WhatsApp
// message) deliberately stays in the products' English names — only what the
// customer sees on the page is localized.

const en = {
  titleWord: "Order",
  referral: "🎁 You were referred — you have a welcome discount on your first order",
  deliveryDays: "Posting days",
  orderBy: "Order by",
  beforeVal: "%1 the day before",
  madeToOrder: "Made to order · closes %1 the day before",
  sPickDay: "Pick a posting day",
  sWhat: "What would you like?",
  sYourDetails: "Your details",
  yourName: "Your name",
  namePh: "e.g. Aisyah",
  whatsappNo: "WhatsApp number",
  whatsPh: "e.g. 012-345 6789",
  waSub: "We use this to confirm your order and send your payment QR — we'll never spam you.",
  howGet: "How will you get your order?",
  courier: "Post (nationwide)",
  selfCollect: "Collect (local)",
  addressLabel: "Postal address",
  addressPh: "Full address — street, area, town & postcode",
  addressSub: "We post nationwide — your treats are made on the day you pick and posted to this address.",
  noteLabel: "Note (optional)",
  notePh: "Allergies, extras, anything…",
  sTrack: "Track your order",
  trackHint: "Placed an order? Enter the order number from your confirmation (it starts with <strong>#</strong>, e.g. #A3F9C2).",
  trackPh: "e.g. A3F9C2",
  trackBtn: "Track",

  items: "%1 items",
  oneItem: "1 item",
  placeOrder: "Place order",
  sending: "Sending…",
  soldOut: "Sold out",
  onlyLeft: "Only %1 left",
  noDates: "No upcoming posting days right now — check back soon.",
  noOpenDates: "All upcoming posting days are full right now — check back soon.",

  confirmAddWaTitle: "Please add your WhatsApp number.",
  confirmAddWaBody: "We use it to confirm your order and send your payment QR.",
  confirmAddrTitle: "Please add your postal address.",
  confirmAddrBody: "We post nationwide — your treats can't be sent without your full address (street, area, town & postcode).",
  confirmClosedTitle: "That day's orders are closed.",
  confirmClosedBody: "Orders for this day close at %1 the day before — please pick a new posting day.",
  confirmChangedTitle: "Your order changed just now.",
  confirmChangedBody: "Something sold out while you were ordering — we've fixed your cart to match what's left.",
  confirmChangedSub: "Please review your order and tap Place order again.",
  sendingToBakery: "Sending your order…",
  orderRecvTitle: "🎉 Order received!",
  orderRecvBody: "%1 has your order.",
  orderRecvThanksBody: "Thanks %1! %2 has your order.",
  orderRecvLine: "📅 %1 · %2 · RM%3",
  orderRecvSub: "Your order is in — we'll WhatsApp you once we confirm it.",
  failTitle: "We couldn't send your order just now.",
  failBody: "Don't worry — send your order on WhatsApp so it isn't lost.",
  failOpened: "WhatsApp has opened with your order — press Send so it isn't lost.",
  failLink: "📲 Send your order via WhatsApp",
  failRetry: "Please try again in a moment.",

  trackEnter: "Enter your order number to track it.",
  trackUnavailable: "Tracking isn't available right now.",
  trackLooking: "Looking up your order…",
  trackNotFound: "We couldn't find order #%1. Check the number in your confirmation message — it's the 6 characters after the #.",
  orderCode: "Order #%1",
  forCustomer: "For %1",
  trkNew: "New",
  trkConfirmed: "Confirmed",
  trkPaid: "Paid",
  trkBaking: "Preparing",
  trkReady: "Packed",
  trkDelivered: "Delivered",

  devBy: "Website by",
  devWa: "WhatsApp the developer",
};

const zh = {
  titleWord: "订购",
  referral: "🎁 经由好友推荐 — 首次下单即可享受专属优惠",
  deliveryDays: "发货日",
  orderBy: "下单截止",
  beforeVal: "发货日前一天 %1 前",
  madeToOrder: "按订单制作 · 发货日前一天 %1 截单",
  sPickDay: "选择发货日",
  sWhat: "您想要什么？",
  sYourDetails: "您的资料",
  yourName: "您的名字",
  namePh: "例如：Aisyah",
  whatsappNo: "WhatsApp 号码",
  whatsPh: "例如：012-345 6789",
  waSub: "我们会用这个号码确认订单并发送付款二维码，绝不会骚扰您。",
  howGet: "您希望怎样收货？",
  courier: "邮寄（全马）",
  selfCollect: "自取（本地）",
  addressLabel: "邮寄地址",
  addressPh: "完整地址 — 街道、地区、市镇与邮编",
  addressSub: "我们提供全马邮寄——您的零食会在所选发货日制作，并寄往这个地址。",
  noteLabel: "备注（可选）",
  notePh: "过敏原、额外要求、其它…",
  sTrack: "查询订单",
  trackHint: "已经下单了？请输入确认讯息里的订单编号（以 <strong>#</strong> 开头，例如 #A3F9C2）。",
  trackPh: "例如：A3F9C2",
  trackBtn: "查询",

  items: "%1 项",
  oneItem: "1 项",
  placeOrder: "提交订单",
  sending: "发送中…",
  soldOut: "已售完",
  onlyLeft: "仅剩 %1 份",
  noDates: "目前没有可预订的发货日 — 请稍后再来。",
  noOpenDates: "近期发货日均已满 — 请稍后再来。",

  confirmAddWaTitle: "请填写您的 WhatsApp 号码。",
  confirmAddWaBody: "我们会用它确认订单并发送付款二维码。",
  confirmAddrTitle: "请填写您的邮寄地址。",
  confirmAddrBody: "我们提供全马邮寄——没有完整的邮寄地址（街道、地区、市镇及邮编）就无法寄出您的零食。",
  confirmClosedTitle: "该日的订单已截止。",
  confirmClosedBody: "此日订单需在发货日前一天 %1 前下单 — 请另选一个发货日。",
  confirmChangedTitle: "您的订单刚刚有变动。",
  confirmChangedBody: "下单期间有零食售完了 — 我们已根据剩余数量更新您的购物车。",
  confirmChangedSub: "请再次确认订单并点击「提交订单」。",
  sendingToBakery: "正在发送您的订单…",
  orderRecvTitle: "🎉 订单已收到！",
  orderRecvBody: "%1 已收到您的订单。",
  orderRecvThanksBody: "谢谢 %1！%2 已收到您的订单。",
  orderRecvLine: "📅 %1 · %2 · RM%3",
  orderRecvSub: "订单已收到 — 确认后我们会通过 WhatsApp 通知您。",
  failTitle: "暂时无法发送您的订单。",
  failBody: "别担心 — 请通过 WhatsApp 发送订单，以免遗漏。",
  failOpened: "WhatsApp 已打开并带上您的订单 — 请按「发送」。",
  failLink: "📲 通过 WhatsApp 发送订单",
  failRetry: "请稍后再试一次。",

  trackEnter: "请输入订单编号查询。",
  trackUnavailable: "现在暂时无法查询。",
  trackLooking: "正在查询您的订单…",
  trackNotFound: "找不到订单 #%1。请检查确认讯息中的编号 — 即 # 号后的 6 个字符。",
  orderCode: "订单 #%1",
  forCustomer: "顾客：%1",
  trkNew: "新订单",
  trkConfirmed: "已确认",
  trkPaid: "已付款",
  trkBaking: "准备中",
  trkReady: "已打包",
  trkDelivered: "已送达",

  devBy: "网站制作：",
  devWa: "用 WhatsApp 联系开发者",
};

const ms = {
  titleWord: "Tempahan",
  referral: "🎁 Anda dirujuk — anda ada diskaun sambutan untuk tempahan pertama",
  deliveryDays: "Hari pos",
  orderBy: "Tempahan ditutup",
  beforeVal: "%1 sehari sebelumnya",
  madeToOrder: "Dibuat mengikut tempahan · tutup %1 sehari sebelum",
  sPickDay: "Pilih hari pos",
  sWhat: "Apa yang anda mahukan?",
  sYourDetails: "Maklumat anda",
  yourName: "Nama anda",
  namePh: "cth. Aisyah",
  whatsappNo: "Nombor WhatsApp",
  whatsPh: "cth. 012-345 6789",
  waSub: "Kami guna nombor ini untuk sahkan tempahan dan hantar QR pembayaran — kami tidak akan spam anda.",
  howGet: "Macam mana anda mahu terima tempahan?",
  courier: "Pos (seluruh negara)",
  selfCollect: "Ambil sendiri (setempat)",
  addressLabel: "Alamat pos",
  addressPh: "Alamat lengkap — jalan, kawasan, bandar & poskod",
  addressSub: "Kami hantar ke seluruh negara — snek anda dibuat pada hari yang anda pilih dan dihantar ke alamat ini.",
  noteLabel: "Nota (pilihan)",
  notePh: "Alahan, tambahan, apa-apa sahaja…",
  sTrack: "Semak tempahan anda",
  trackHint: "Sudah menempah? Masukkan nombor tempahan dari mesej pengesahan (bermula dengan <strong>#</strong>, cth. #A3F9C2).",
  trackPh: "cth. A3F9C2",
  trackBtn: "Semak",

  items: "%1 item",
  oneItem: "1 item",
  placeOrder: "Hantar tempahan",
  sending: "Menghantar…",
  soldOut: "Habis",
  onlyLeft: "Tinggal %1 sahaja",
  noDates: "Tiada tarikh pos buat masa ini — sila datang lagi nanti.",
  noOpenDates: "Semua hari pos akan datang penuh buat masa ini — sila datang lagi nanti.",

  confirmAddWaTitle: "Sila masukkan nombor WhatsApp anda.",
  confirmAddWaBody: "Kami guna untuk sahkan tempahan dan hantar QR pembayaran anda.",
  confirmAddrTitle: "Sila masukkan alamat pos anda.",
  confirmAddrBody: "Kami hantar ke seluruh negara — snek anda tidak dapat dihantar tanpa alamat lengkap (jalan, kawasan, bandar & poskod).",
  confirmClosedTitle: "Tempahan untuk hari itu sudah ditutup.",
  confirmClosedBody: "Tempahan untuk hari ini ditutup pada %1 sehari sebelum — sila pilih hari pos baharu.",
  confirmChangedTitle: "Tempahan anda baru sahaja berubah.",
  confirmChangedBody: "Ada snek yang habis semasa anda menempah — kami telah kemas kini troli anda mengikut apa yang tinggal.",
  confirmChangedSub: "Sila semak tempahan anda dan tekan Hantar tempahan sekali lagi.",
  sendingToBakery: "Menghantar tempahan anda…",
  orderRecvTitle: "🎉 Tempahan diterima!",
  orderRecvBody: "%1 telah menerima tempahan anda.",
  orderRecvThanksBody: "Terima kasih %1! %2 telah menerima tempahan anda.",
  orderRecvLine: "📅 %1 · %2 · RM%3",
  orderRecvSub: "Tempahan anda telah diterima — kami akan WhatsApp anda sebaik sahaja disahkan.",
  failTitle: "Kami tidak dapat menghantar tempahan anda buat masa ini.",
  failBody: "Jangan risau — hantar tempahan anda melalui WhatsApp supaya ia tidak hilang.",
  failOpened: "WhatsApp telah dibuka dengan tempahan anda — tekan Hantar supaya ia tidak hilang.",
  failLink: "📲 Hantar tempahan anda melalui WhatsApp",
  failRetry: "Sila cuba lagi sebentar lagi.",

  trackEnter: "Masukkan nombor tempahan anda untuk disemak.",
  trackUnavailable: "Semakan tidak tersedia buat masa ini.",
  trackLooking: "Mencari tempahan anda…",
  trackNotFound: "Kami tidak dapat mencari tempahan #%1. Sila semak nombor dalam mesej pengesahan anda — iaitu 6 aksara selepas #.",
  orderCode: "Tempahan #%1",
  forCustomer: "Untuk %1",
  trkNew: "Baharu",
  trkConfirmed: "Disahkan",
  trkPaid: "Dibayar",
  trkBaking: "Sedang disediakan",
  trkReady: "Dibungkus",
  trkDelivered: "Dihantar",

  devBy: "Laman web oleh",
  devWa: "WhatsApp pembangun",
};

export const STORE = { en, zh, ms };
