// views/guide.js — a plain-English guide to the shared engine, for THIS app
// only (the bakery doesn't get it). Explains, in everyday words, that munchies
// and the bakery run the same engine, which step maps to which name, and what
// lives where. Content master kept in Claude's memory; refresh here whenever an
// engine sync lands so new-version notes stay current.

import { el, button } from "../ui.js";
import { ENGINE_VERSION } from "../version.js";

// Navigate by hash so app.js isn't needed at import time.
const navigate = (hash) => { location.hash = hash; };

export function renderGuide(root, state) {
  root.replaceChildren(
    el("div", { class: "btn-row", style: "margin-bottom:10px" },
      button("← Back", () => navigate("#/more"), "ghost")),

    introCard(),

    el("h2", { class: "section" }, "One engine, two shops"),
    ...analogyRows([
      ["The engine",
        "The shared software underneath BOTH your businesses. It decides how every screen, button, order and sync works.",
        "Like the same car engine fitted under two different shop signs — one for your bakery, one for Munchies Furkidz."],
      ["Engine updates (syncing)",
        "New engine improvements are built on your bakery app first, then copied into this one, so the two always work the same way.",
        "Like perfecting a new kitchen gadget in one kitchen, then installing the same gadget in the other."],
      ["Engine version",
        "A numbered batch of improvements. Right now both apps run Engine v" + ENGINE_VERSION + ".",
        "A version sticker on the machine — check this More screen and your bakery's More screen; they should match."],
      ["Your words vs the engine's",
        "The engine keeps ONE internal name for every step. Each of your shops shows its own word on screen.",
        "One kitchen timer, two different labels stuck on it."],
    ]),

    el("h2", { class: "section" }, "Same step, different name"),
    ...analogyRows([
      ["Preparing (this app)",
        "The step where an order is being made. The bakery calls this same step “Baked” — it's the identical engine step, just named for pet treats.",
        "Two shop signs, same room behind them."],
      ["Posting day (this app)",
        "Your production days — Monday / Wednesday / Friday. The bakery says “bake day”; yours is a “posting day” because your treats are posted nationwide.",
        "Same schedule on the calendar, different name in each shop."],
      ["Post vs Collect",
        "How an order reaches the customer: Post (nationwide) with a flat fee, or Collect (local). The bakery uses “Courier / Collect”.",
        "Same two ways to hand something over, your own labels."],
    ]),

    el("h2", { class: "section" }, "What stays yours alone"),
    ...analogyRows([
      ["Your cloud cabinet",
        "Orders, products, your “On hand” stock, the postage fee you set and more sync between YOUR phones through your OWN online cabinet (Supabase). Customers never see any of it.",
        "A notebook in the sky — but each business has its OWN notebook. This app never touches your bakery's records."],
      ["Your postage fee",
        "The RM8 posting fee is quoted only by you, on your WhatsApp confirmations. It syncs between your phones — whatever you set last wins — so both quote the same figure. It is never published to the storefront: customers only hear the exact amount from you.",
        "The private price list you and your other till share — not the menu hanging in the window."],
      ["On this phone only",
        "A few things really do stay on the phone you're using: your app PIN and the cloud-login email & password you type in. Your “On hand” stock is NOT one of these, and neither is the postage fee — both sync like the rest of your records.",
        "A sticky note on the till — not copied into the sky notebook."],
      ["Your branding & prices",
        "Domain munchies.com.my, product names, prices, photos, WhatsApp/Instagram — all yours, per shop.",
        "The sign, the menu and the prices are yours; only the machinery underneath is shared."],
      ["Backup file",
        "“Backup” in Settings makes a full copy of your records to keep safe.",
        "A photocopy of the whole notebook, put away in a drawer."],
    ]),

    el("h2", { class: "section" }, "Newest in the engine"),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The holiday tint sits on the dates at Orders, and a computer names a day just by pointing at it (Engine v88)"),
      el("p", { class: "card-sub" },
        "On the Orders screen each posting day carries its booking count, and that count sat under the date number — which pushed the number above the middle of its row, so the holiday wash sat lower than the dates it was meant to be tinting, and the dates did not line up with each other. The count now sits at the foot of the day, every date sits on one line, and the tint runs through that line. Nothing else about that calendar moved."),
      el("p", { class: "hint" },
        "And on a computer, resting the mouse pointer on a marked day now shows its name on its own, exactly as the customer's page does. It is deliberately only for a pointer that can hover: a phone keeps the tap, so a finger sweeping across a run of days on the Availability or Delivery Dates calendars never drags a bubble along with it.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Tap a marked day and it tells you its name — on every calendar (Engine v87)"),
      el("p", { class: "card-sub" },
        "Engine v85 drew your marks on all five of the app's month calendars, but only as colour — a wash and a band, with nothing to say which holiday it was. Your customer's own page has answered this since its calendar arrived, so the app now does the same thing, in the same look: a small dark bubble above the day names it (“Malaysia Day”), and it goes away as soon as you tap anywhere else."),
      el("p", { class: "hint" },
        "Nothing else about the tap changed: at Orders it still opens the day, on a product's Availability calendar it still marks or unmarks the sell day, on Delivery Dates it still starts the range you are about to mark. A day inside two marks takes the name of the shorter one — the same rule the colours already follow — and a day already gone is never named. Two kinds of day that could not be read at all can now: a marked day at Orders you do not post for, and a day on Delivery Dates that is already one of your posting dates. The Order date boxes name their day above the date rather than above a day of the month, because those boxes fold their calendar the moment a day is picked.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The marks on the Orders screen now sit on their days (Engine v86)"),
      el("p", { class: "card-sub" },
        "The days on the Orders screen are taller than the days anywhere else, because a posting day there carries its booking count under its number. That had two effects. A holiday band was stretched to fill its week row, so it came out deeper there — and deeper in the weeks holding a posting day than in the others — so one holiday's own band changed depth from row to row inside a month. And a plain day kept the app's usual height inside a taller row, so a single-day mark was drawn a few pixels higher on a day you do not post for than on a day you do. A band is now a sheet of one depth centred on its row, every day of that month is one height whether or not it is a posting day, and today on that screen glows around its number."),
      el("p", { class: "hint" },
        "Only the drawing changed. The shop's calendar and your Delivery Dates calendar look exactly as before — their days are all one height, so they never had this — and no mark was added, moved or removed.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Your marked days are drawn on every calendar in the app (Engine v85)"),
      el("p", { class: "card-sub" },
        "Until now a holiday only appeared on the customer's calendar and on the Delivery Dates screen you marked it on. Every other calendar drew a plain month: the month calendar at the top of Orders, the little Order date calendars in the new-order form and the Edit pop-up, the posting-day picker inside that pop-up, and a product's Availability calendar where you mark the days it sells. A holiday you were planning around was invisible on every screen you actually plan on. All of them now draw your marks, in the same two shapes and the same colours as the Delivery Dates calendar — a see-through band across a run, deeper the shorter the run, and a box for a single day."),
      el("p", { class: "hint" },
        "A mark on a day you do not post for is drawn too, on the dimmed day, since that is the only way a holiday on a quiet day can be seen at all. Two small pieces of the drawing were tidied while moving it: the green tint on a day a product sells is now a see-through wash rather than a flat fill, so a holiday band running behind it still shows through instead of vanishing on exactly the days you sell; and a marked day that happens to be today keeps today's soft glow.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A day you marked is one gentle wash everywhere (Engine v84)"),
      el("p", { class: "card-sub" },
        "A mark used to be drawn one of two ways, decided by a single question: is this a day you post for? On a day you post for, the mark went pale so the green “you can order” ring stayed the first thing the eye read; on a day you don't, it was a full-colour solid block with the number turned white. So the same kind of holiday could look like two different things — and a mark quietly changed its own appearance as the posting window moved towards it. A mark is now only ever a see-through wash of its own colour, and its depth follows how long the mark runs: a one-day holiday the deepest, a long school break the palest."),
      el("p", { class: "hint" },
        "The customer's calendar and your own Delivery Dates calendar read that depth from the same place, so a day wears exactly the same mark on both sides of the shop and in every month. Nothing is a solid block of colour any more, which also means the date number and the green posting pill always read on top of a mark, whether or not you post that day.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Marking a holiday now tells the shop straight away (Engine v83)"),
      el("p", { class: "card-sub" },
        "A day you mark on the Delivery Dates calendar is drawn on the customer's own calendar. But saving a mark only ever sent your posting days to the cloud — it never sent the customer's page anything — so the marks reached the shop only by accident, whenever you next happened to save a product or a setting. Mark the holiday, open the shop, and nothing had changed. Now the same save does both: marking a day, removing a mark, loading a set from the standard list, or renaming or recolouring one all republish the customer's page within a couple of seconds, exactly the way editing a product does."),
      el("p", { class: "hint" },
        "One tap to catch up the marks you already have: the fix sends the marks from now on, and the ones already on your calendar have never been sent at all, so open More → Settings → Storefront and tap Publish now once. After that the shop's calendar follows your marks by itself. Nothing else about a mark changed: it is still only ever something to see while planning, it still never adds or removes a posting day, and a name you typed yourself still never leaves your phone.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A product's selling days are marked on its own calendar (Engine v82)"),
      el("p", { class: "card-sub" },
        "Until today a product could say only two things about when: a notice period, and one from-date and to-date for a season. You asked to set it freely instead, so those two date boxes have become a card you mark — the Availability card, sitting under Daily limit and folded until you tap its title. Folded, its title tells you what is marked, so the Products list alone tells you a product's selling days: “Every day”, or “Sat & Sun”, or “1-24 Dec 2026”. Inside, it is a month calendar and four gestures: tap a weekday letter (M, T, W…) and every one of that weekday in the month shown is marked; tap one day to mark just that day; slide your finger across several days and the whole run is marked; and tapping or sliding over a day that is already marked takes it back."),
      el("p", { class: "hint" },
        "Nothing carries over into the next month — that is the point of it, so a December-only set stays December-only and January starts with nothing marked. A product whose card you have never opened sells on every posting day exactly as before, so nothing on your live shop moves until you mark it. A period that crosses a month or a year is one mark with two ends you can stretch, and a small x removes a mark whole. On the order page a day a product is not sold for is not a note — the product is simply not there; the one rule that keeps its note is the notice period, because that product IS sold that day, it only has to be ordered earlier. The old From/To boxes are gone, and a product that had them opens with that period already sitting in the card, so nothing you set before is lost.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A holiday you marked is drawn on the shop the way your own calendar draws it (Engine v81)"),
      el("p", { class: "card-sub" },
        "The marks were already reaching the shop; it was only their shape that differed, and a mark that looks different on the customer's page than on yours is a mark your customer has to learn twice. The shop had been drawing each marked day as its own flat pale square, so a holiday running over a week read as a row of separate blocks where your own calendar shows one continuous shape. A holiday running over several days is now one unbroken see-through band across them, deeper the shorter the run, and a single-day holiday is a solid box in its full colour, a touch narrower so a longer band still peeks out at its sides."),
      el("p", { class: "hint" },
        "The one place it gives way is a day you post for: green is the colour the posting ring uses and a solid box would swallow it, so the box goes pale there and the green ring stays the first thing the eye reads — the mark is still there, and the day is still named on a tap. Your own typed-in days still never reach the shop: only a day that is, by name and date, one of the built-in standard days can be published, so your own notes stay private to your phone.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Today glows, a holiday is a tint you can tap, and Orders leads with the same calendar (Engine v80)"),
      el("p", { class: "card-sub" },
        "Three small things, all pulling the same way: a calendar should read the same on both sides of the shop, and nothing drawn on it should look like something it is not. On the shop, today no longer wears a little red rectangle — it traced the day's number as a box on a day you do not post for — and is now a gentle glow that breathes around the number, sitting happily on a posting day too (the green ring says you can order for this day, the soft glow says it is today). A holiday you marked is a pale wash of its own colour over the whole day, deliberately neither a ring nor a dot, because a ring is what “you can order for this day” looks like; tap it — or on a computer, rest the mouse on it — and a small bubble names the day. And the Orders screen's sideways date strip is now the same month calendar the customer sees: posting days ringed in green with how booked it is under each (“3/12”, or FULL), a closed day's count in red, and a day already gone dimmed but still opening."),
      el("p", { class: "hint" },
        "The ＋ New order card now arrives folded and reads in the order you think in: the month calendar first, then the customer's details, then the items — it stays open after you add an order. The Edit pop-up's Delivery day calendar is simply there now rather than behind a button, and both pop-up and card read day, then details, then items. The “Holidays” line under the shop's grid is gone; the name comes out on a tap instead.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The customer picks a posting day on a calendar, and so do you in the app (Engine v79)"),
      el("p", { class: "card-sub" },
        "The shop used to show its posting days as a row of date chips laid out sideways. Under Pick a posting day the customer now sees a month calendar — one month at a time, with arrow buttons either side of the month's name to look ahead or back. The days you are taking orders for are picked out in green; every other day of the month is plain and cannot be tapped. They tap a green day and the day they chose is written out in words just underneath — “Your posting day: Wed, 16 Sep” — with a “Sold out: …” line when a day in the month is full. The first open day is already chosen for them when the page opens, so ordering can never be blocked by forgetting to tap."),
      el("p", { class: "hint" },
        "In the app the same little calendar now stands wherever you name a date. The Edit pop-up's Delivery day is no longer a drop-down: it names the order's current day and opens a calendar beneath it, with every day still to come tappable plus the order's own day even if it has passed. The Order date box is a calendar too, with a Today shortcut. And the ＋ New order card has gained a Delivery day picker at its top — tap another green day and the whole screen moves to it, so the product list you choose from is always the one that is actually sellable for the day you picked. Only the standard days you have marked reach the customer; a day you typed yourself stays private to your phone, and marking nothing leaves the shop's calendar carrying nothing.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The calendar's Add buttons now say what they do (Engine v78)"),
      el("p", { class: "card-sub" },
        "On the Delivery Dates screen, “Mark an occasion” carried a small button reading “＋ Add occasion”. That name didn't tell you it opens a ready-made list of Malaysia's holidays and fun days, all ticked and waiting — so you had to open it to find out. It now reads “＋ Load standard occasions”, and the window it opens is titled the same."),
      el("p", { class: "hint" },
        "Inside that window there were two buttons both called “Add” — the big one at the bottom that files the days you ticked, and a smaller one in the “My own day” strip just above it, which files a day you name yourself. Reaching for “Add” and hitting the wrong one gave you “Type a name first”, for a day you never meant to name. The smaller one is now spelled out as “Add my own day”, so the only plain Add in the window adds the days you ticked. Nothing else on that screen moved.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The translated-text card says what a blank line means (Engine v77)"),
      el("p", { class: "card-sub" },
        "A wording fix on top of v76's fold-away card. The greyed line in a product's translated-text card used to end “blank keeps English”; it now finishes “if blank, it will be filled with English” — stating what the customer gets, rather than what the line does. The card's own sub-line ends the same way."),
      el("p", { class: "hint" },
        "The rule underneath is unchanged: delete what is in a line and the greyed suggestion and its arrow come back exactly as before, → still takes the words, and ↻ still re-translates that one line.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The translated text folds away, filled a line at a time (Engine v76)"),
      el("p", { class: "card-sub" },
        "The translated-text corner of a product was the busiest part of the screen: always open, eight lines each with its own “Translate this one” button, two “Fill all” buttons above, and an “auto” tag to decode. It is now one quiet card that starts shut and stays shut — it's setup, not daily use. Tap the title to open it, tap anywhere outside to fold it back. Opened, each empty line shows its translation already worked out as the app's standard greyed suggestion with the → at its right edge — the same gesture as every other suggested box — and taking it swaps the arrow for a ↻ that re-translates just that line. Typing your own words hides the ↻ (the line is yours); a blank line keeps the English."),
      el("p", { class: "hint" },
        "A product you never open the card for still reads in all three languages on the shop — the auto-translate still runs after every save and publish.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The green glow on a jumped-to order waits for you (Engine v75)"),
      el("p", { class: "card-sub" },
        "Tapping a row in the New Orders inbox (or a result in Find an order) takes you to that order's posting day and lights the order up green — but the glow faded after under two seconds, which is no time at all while your eye is still travelling down a long day, and you were left hunting for a row that was no longer lit. The glow now keeps pulsing until your finger arrives on the row, and stops the moment you reach it."),
      el("p", { class: "hint" },
        "If your phone is set to reduce motion, the green ring holds steady instead of pulsing — it still stays until you reach the row.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The little arrow in an empty box keeps working (Engine v74)"),
      el("p", { class: "card-sub" },
        "Engine v73 added the small right-arrow at the right edge of a box showing a greyed example: press → on a keyboard, or tap the arrow, and the example drops in as real text. On a phone the tap worked the first time and then stopped — once you had tapped into any box, tapping the arrow on the next one did nothing, because taking a suggestion opened the phone's keyboard, which shrank and shifted the page under your thumb. Taking a suggestion no longer opens the keyboard, the strip that counts the tap is about half again as wide, and the tap is judged against the box's own edge as well as its place on the page — so a thumb landing a little wide still counts."),
      el("p", { class: "hint" },
        "The drawn arrow is kept exactly as it was — same size, same place — and a tap on the greyed example itself is still an ordinary tap that puts the cursor there.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Change windows, moving an order, your Policies, and a one-tap suggestion (Engine v73)"),
      el("p", { class: "card-sub" },
        "Four things. Each product can now carry a “Changes or cancellations (days before delivery)” box: the customer reads the sentence on the product's card and again on their green “Order received!” card, and a mixed basket shows the strictest (largest) figure. Blank means no window is stated and 0 states no advance limit — neither ever blocks you, who move every order by hand. An order's posting day can now be changed in the app instead of deleted and re-typed (a deletion reads as a cancellation): the Edit-order pop-up gains a “Delivery day” select of every day still to come, and saving moves the whole order across, warning softly if the new day falls inside the customer's window. A Policies box in Settings → Storefront holds your own cancellation and refund wording — typed once in English, translated to Chinese and Bahasa Malaysia, and drawn on the shop under Track your order in the visitor's language, with the line breaks you typed. Blank hides the section."),
      el("p", { class: "hint" },
        "And app-wide, where an empty box shows the app's greyed recommendation, the right arrow — or a tap on the small arrow drawn at the box's right edge — accepts it as real text, like an AI chat prompt. Your Supabase email, key and password boxes and the sign-in fields carry no arrow, so a made-up login can never be accepted by accident.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Sold-out notes read in the customer's language (Engine v72)"),
      el("p", { class: "card-sub" },
        "Two corners of your order page used to stay English whichever language a customer picked: the small note on a product that can't be ordered for the posting day they chose (that it only opens from a date, only runs up to one, or that orders close so many days ahead), and the notes that appear above the menu when the page had to change their basket — something that just sold out, or a quantity trimmed to what is left."),
      el("p", { class: "hint" },
        "Both now read in English / 中文 / BM with everything else, and the date in the note is written in their language too — so nothing English can slip into a Chinese or Malay page. An English visit reads exactly as it did.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The order page's language buttons answer instantly (Engine v71)"),
      el("p", { class: "card-sub" },
        "Tapping English / 中文 / BM on your order page used to reload the whole page — re-downloading the menu, the “only N left” numbers and your saved order-page settings, which is a pause on a phone. It now switches in place, like your homepage already did: the words change the instant they tap and nothing is downloaded again."),
      el("p", { class: "hint" },
        "Anything the customer had already done is left untouched — their basket, the posting day they chose, and the name, WhatsApp number and address they typed. If they were looking up an order, that card re-reads in the new language too.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "An order keeps the name and price it was sold at (Engine v70)"),
      el("p", { class: "card-sub" },
        "An order now remembers what it was sold as and what it was sold for, frozen the moment you take it — from the shop or typed in by hand. Rename a product or change its price later and your past orders, the labels, customer spend and the tracking page a customer sees all stay on the old name and price. A product you delete afterwards still shows what it was that someone bought."),
      el("p", { class: "hint" },
        "Deliberately swapping a line to a different product when you edit an order picks up the new price — you changed what is being sold. A line you leave alone keeps the price it was sold at. Orders from before today are stamped once with what they were already showing.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Either place updates the customer (Engine v69)"),
      el("p", { class: "card-sub" },
        "A customer's name and number now follow whichever you edited last. Fix a name with “Edit” on one of their orders and that is the one the list, the history pop-up and the “Hi {name}!” greeting use; open their card, type the name and save, and the card's name is used instead. Neither place is the boss — and because each save writes through to the other, they normally read the same anyway. This only decides the rare case where an old copy and a newer one both sit there."),
      el("p", { class: "hint" },
        "Nothing to set up — your phones pick it up with the next sync.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "One name and one number per customer (Engine v68)"),
      el("p", { class: "card-sub" },
        "A customer's name and WhatsApp number used to live in two places — on their orders and on their customer card — and could disagree. Now saving the card writes the name and number onto every one of their orders, so your labels, messages and customer list all follow; and fixing a wrong number with “Edit” on an order carries back to their card too. Leaving a box empty means “leave it as it is” — it never wipes a number your confirmations need. Anyone you renamed before today gets put right automatically the first time this version opens."),
      el("p", { class: "hint" },
        "Correcting a number brings that customer's bring-a-friend credits across with it, and renaming someone with no number on file no longer loses them.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A “No name” customer keeps the name you save (Engine v67)"),
      el("p", { class: "card-sub" },
        "When a customer reaches you without a name — a storefront order that carried none — their row in the customer book now takes the name you save on their profile. Open the person, tap “Add details”, type their name (and the pet's name, likes and so on) and save: the row, the finder and the “Hi {name}!” WhatsApp greeting all use it from then on. Before, the row only ever read the order, so an unnamed customer stayed “No name” no matter what you typed."),
      el("p", { class: "hint" },
        "Your order's own name still wins when there is one — the saved profile name only fills in for someone recorded anonymously.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Product text that translates itself into 中文 & Bahasa Malaysia (Engine v66)"),
      el("p", { class: "card-sub" },
        "When you save or publish a product, the app quietly fills the Chinese and Malay versions of its name, description, selling unit and feeding tip — machine-made from your English, free, whenever you're online. Each translated box is tagged “auto”. Type over any box and it becomes yours: your own wording is never overwritten. In Products → Edit you can also tap “Fill all 中文” or “Fill all Bahasa Malaysia”, or fill one line at a time with ↻. Blank English means no translation, and if you later change an English line, that box is re-filled to match."),
      el("p", { class: "hint" },
        "A shopper reading in that language then sees the product in their own words on your order page — a translation only ever exists because your English version does.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Products in three states: Draft, On the shop, Hidden (Engine v66)"),
      el("p", { class: "card-sub" },
        "Products now sit in three separate lists. A brand-new product starts as a Draft — fully built but not for sale until you Publish it. On the shop holds what customers can actually order. Hidden is a product you took down but want to keep (history and recipe stay). Publish a draft to start selling it; Hide any live product to pause it."),
      el("p", { class: "hint" },
        "Drafts and Hidden products never appear on your storefront and can't be ordered, so building a new recipe can't accidentally go live.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Copy the referral follow-up in your customer's language (Engine v66)"),
      el("p", { class: "card-sub" },
        "In a customer's profile, before you tap “🎉 Copy follow-up”, you can pick the message's language — English, 中文 or Bahasa Malaysia. The whole check-in, including the product's translated name and feeding tip, is written in that language, so the text you paste into WhatsApp already speaks in your customer's own words. English stays the default."),
      el("p", { class: "hint" },
        "The follow-up is the warm check-in that slides the bring-a-friend link in after a delivery.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Reviews to publish, one at a time (Engine v65)"),
      el("p", { class: "card-sub" },
        "More → Reviews now shows each review one at a time, exactly as it will look on your homepage — the ones waiting to be published first. Publish puts it up, Take down hides it, Delete removes it for good, and each action moves you on to the next one. Home and the ⭐ Reviews menu row show an “N waiting” count whenever new reviews are sitting on you."),
      el("p", { class: "hint" },
        "No autoplay on purpose: it's a deciding screen, not a slideshow — the review in front of you stays until you act on it.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "中文 / English / Bahasa Malaysia — the whole site (Engine v64)"),
      el("p", { class: "card-sub" },
        "Your homepage and ordering page now speak three languages. Tap English / 中文 / BM at the top and every word — buttons, delivery days, the order form — switches over on the spot (your phone remembers the choice). You can also give a product a Chinese or Malay shop name in Products, so the card reads 鸡肉干 or Jerky Ayam while orders still track the English name."),
      el("p", { class: "hint" },
        "Each visitor picks their own language, so one link works for every customer.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Homepage reviews as a carousel + a website credit (Engine v64)"),
      el("p", { class: "card-sub" },
        "The “What customers say” section on your homepage now swipes — readers drag left or right through the reviews you've published, or tap the dots. And if your website was made for you, Settings → Website & developer lets you name who built it: a small “Website by …” credit then shows at the bottom of the homepage and order page, and More → About gains a WhatsApp and email row to reach them."),
      el("p", { class: "hint" },
        "The same developer is who the wish list emails. Add a wish on More and it can send the whole list to them automatically — or tap “✉ Email the full list” to send it yourself.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A Customers tab with profiles & a finder (Engine v63)"),
      el("p", { class: "card-sub" },
        "Customers now has its own tab in the bottom bar, and each person can carry a small profile — their pet's name, a photo, what they like, what to avoid, and a note. Type in the finder box to narrow the list by name, number, pet's name or favourite product. Dogs and cats both fit. The Purchase Order screen moved under More to make room, and photos you pick are shrunk to a tiny thumb before saving."),
      el("p", { class: "hint" },
        "Profiles ride the same customer list on both your phones, so what you learn about a regular on one phone is there on the other.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "An always-on Upcoming holidays card (Engine v63)"),
      el("p", { class: "card-sub" },
        "On Home, the “Upcoming holidays” card now always shows: with nothing marked it explains how to add days on the Delivery calendar, and once more than three are coming up the list scrolls instead of dropping the rest."),
      el("p", { class: "hint" },
        "Before, a quiet week made the card vanish — now it's a steady reminder either way.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Engine version, wish list & change history (Engine v63)"),
      el("p", { class: "card-sub" },
        "More now shows which engine version you're on, has a wish list where you can jot ideas for the app (a tick stays ticked until you untoggle it), and links to the full change history from v54 onwards as a PDF you can read on any phone."),
      el("p", { class: "hint" },
        "Think of the wish list as your idea notebook for the software, kept with the app itself.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Amber “not sharing” strip + read-only backup View (Engine v62)"),
      el("p", { class: "card-sub" },
        "When a phone isn't on the shared cloud — shared data off, never set up, or signed out — an amber strip now shows on every screen so you always know. And each copy under Settings → Backup & safety has a View button: it opens that copy read-only (its orders, prices and stock), so you can check an old detail without moving today's data."),
      el("p", { class: "hint" },
        "Viewing a backup changes nothing — no writes, no reload — it's a window into that copy's past.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Cloud backups you can step back to (Engine v61)"),
      el("p", { class: "card-sub" },
        "Every day you open the app signed in, a full copy of your records quietly saves to your own cloud — a Daily copy the first time the app opens each day, a Weekly copy on Mondays, a Monthly copy on the 1st. It keeps the newest 7 daily, 4 weekly and 3 monthly copies. In Settings → Backup & safety you can Restore your phone back to any copy (a “Before restore” copy is saved first, so you can undo it), Download one as a file, or Delete it. Automatic copies tidy themselves up; Manual ones stay until you delete them."),
      el("p", { class: "hint" },
        "Your cloud copies sit behind the same private login as your shared records — customers never see them. Restore rewinds your phone AND the shared cloud to that copy.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Homepage reviews you approve first (Engine v60)"),
      el("p", { class: "card-sub" },
        "Your homepage can now show a “What customers say” section. Visitors leave a review — a star rating, a few words in English / 中文 / Bahasa Malaysia, and an optional photo — but nothing appears publicly until YOU tap Publish on it, in More → Reviews. New ones sit under Waiting for you; Publish puts it on the homepage, Take down hides it again, Delete removes it for good."),
      el("p", { class: "hint" },
        "Customers post into your own cloud and only your tap makes it public — the same trust step as confirming a storefront order before accepting it.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Tick a whole occasion group at once (Engine v59)"),
      el("p", { class: "card-sub" },
        "On the Delivery calendar → Mark an occasion, the import list groups the ready-made occasions — pet days, people & kindness days, and more — so you can tick a whole group in one tap, then untick any you don't want before adding them all to your calendar. A “My own day” box lets you type any occasion the list doesn't have, e.g. “Pet-treat promo day”."),
      el("p", { class: "hint" },
        "Whole-group ticking saves taps when you want most of a group; the group's master checkbox shows a dash when only some of its days are ticked.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A catalogue of occasions to add (Engine v58)"),
      el("p", { class: "card-sub" },
        "Behind “＋ Add occasion” on the calendar is now a curated list of ready-made special days — Malaysian public holidays plus fun days for pets and people (World Animal Day, National Pet Day, International Cat & Dog Day and similar) — colour-coded red for public holidays, orange for the rest, so the calendar stays easy to read."),
      el("p", { class: "hint" },
        "These are suggestions to import, never automatic — you choose which ones land on your calendar.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A note on each ingredient line (Engine v57)"),
      el("p", { class: "card-sub" },
        "In a product's recipe, every ingredient line can now carry its own short note about that ingredient for this product only — e.g. which cut or brand of chicken, or which variety of sweet potato. It's for your eyes alone: it never appears on the shop, a label, or the product cards. Because it rides on the product like the recipe does, both your phones see it."),
      el("p", { class: "hint" },
        "Sits under the “amount × price” line — the same ingredient can read differently in different products (e.g. chicken in one recipe, duck in another).")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "“Keep at least” reserve stock (Engine v56)"),
      el("p", { class: "card-sub" },
        "On the Ingredients screen, next to “On hand” there's now “Keep at least”. That's your floor — how much you want left on the shelf after a busy posting day. Your shopping list tops an ingredient back up to that level automatically, so you're never caught short. Set it once per ingredient; it syncs with the ingredient, so both your phones see the same number."),
      el("p", { class: "hint" },
        "Runs on top of the “On hand” stock number (Engine v54) — if you track what you have, the app can tell you what to re-buy.")));
}

function introCard() {
  return el("div", { class: "card" },
    el("p", { class: "card-title" }, "Your app, explained"),
    el("p", { class: "card-sub" },
      "Your bakery app and this app are twins under the hood — they share the same engine. This guide explains the engine in everyday words, so the two never feel confusing."),
    el("p", { class: "card-sub" },
      "It lives only here in Munchies Furkidz — your bakery app doesn't need it."));
}

function analogyRows(rows) {
  return rows.map(([term, meaning, analogy]) =>
    el("div", { class: "card" },
      el("p", { class: "card-title" }, term),
      el("p", { class: "card-sub" }, meaning),
      el("p", { class: "hint" }, "Analogy: " + analogy)));
}
