// views/guide.js — a plain-English guide to the shared engine, for THIS app
// only (the bakery doesn't get it). Explains, in everyday words, that munchies
// and the bakery run the same engine, which step maps to which name, and what
// lives where. Content master kept in Claude's memory; refresh here whenever an
// engine sync lands so new-version notes stay current.

import { el, button } from "../ui.js";
import { ENGINE_VERSION } from "../version.js";

// Navigate by hash so app.js isn't needed at import time.
const navigate = (hash) => { location.hash = hash; };

export function renderGuide(root, state) {
  root.replaceChildren(
    el("div", { class: "btn-row", style: "margin-bottom:10px" },
      button("← Back", () => navigate("#/more"), "ghost")),

    introCard(),

    el("h2", { class: "section" }, "One engine, two shops"),
    ...analogyRows([
      ["The engine",
        "The shared software underneath BOTH your businesses. It decides how every screen, button, order and sync works.",
        "Like the same car engine fitted under two different shop signs — one for your bakery, one for Munchies Furkidz."],
      ["Engine updates (syncing)",
        "New engine improvements are built on your bakery app first, then copied into this one, so the two always work the same way.",
        "Like perfecting a new kitchen gadget in one kitchen, then installing the same gadget in the other."],
      ["Engine version",
        "A numbered batch of improvements. Right now both apps run Engine v" + ENGINE_VERSION + ".",
        "A version sticker on the machine — check this More screen and your bakery's More screen; they should match."],
      ["Your words vs the engine's",
        "The engine keeps ONE internal name for every step. Each of your shops shows its own word on screen.",
        "One kitchen timer, two different labels stuck on it."],
    ]),

    el("h2", { class: "section" }, "Same step, different name"),
    ...analogyRows([
      ["Preparing (this app)",
        "The step where an order is being made. The bakery calls this same step “Baked” — it's the identical engine step, just named for pet treats.",
        "Two shop signs, same room behind them."],
      ["Posting day (this app)",
        "Your production days — Monday / Wednesday / Friday. The bakery says “bake day”; yours is a “posting day” because your treats are posted nationwide.",
        "Same schedule on the calendar, different name in each shop."],
      ["Post vs Collect",
        "How an order reaches the customer: Post (nationwide) with a flat fee, or Collect (local). The bakery uses “Courier / Collect”.",
        "Same two ways to hand something over, your own labels."],
    ]),

    el("h2", { class: "section" }, "What stays yours alone"),
    ...analogyRows([
      ["Your cloud cabinet",
        "Orders, products, your “On hand” stock, the postage fee you set and more sync between YOUR phones through your OWN online cabinet (Supabase). Customers never see any of it.",
        "A notebook in the sky — but each business has its OWN notebook. This app never touches your bakery's records."],
      ["Your postage fee",
        "The RM8 posting fee is quoted only by you, on your WhatsApp confirmations. It syncs between your phones — whatever you set last wins — so both quote the same figure. It is never published to the storefront: customers only hear the exact amount from you.",
        "The private price list you and your other till share — not the menu hanging in the window."],
      ["On this phone only",
        "A few things really do stay on the phone you're using: your app PIN and the cloud-login email & password you type in. Your “On hand” stock is NOT one of these, and neither is the postage fee — both sync like the rest of your records.",
        "A sticky note on the till — not copied into the sky notebook."],
      ["Your branding & prices",
        "Domain munchies.com.my, product names, prices, photos, WhatsApp/Instagram — all yours, per shop.",
        "The sign, the menu and the prices are yours; only the machinery underneath is shared."],
      ["Backup file",
        "“Backup” in Settings makes a full copy of your records to keep safe.",
        "A photocopy of the whole notebook, put away in a drawer."],
    ]),

    el("h2", { class: "section" }, "Newest in the engine"),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Either place updates the customer (Engine v69)"),
      el("p", { class: "card-sub" },
        "A customer's name and number now follow whichever you edited last. Fix a name with “Edit” on one of their orders and that is the one the list, the history pop-up and the “Hi {name}!” greeting use; open their card, type the name and save, and the card's name is used instead. Neither place is the boss — and because each save writes through to the other, they normally read the same anyway. This only decides the rare case where an old copy and a newer one both sit there."),
      el("p", { class: "hint" },
        "Nothing to set up — your phones pick it up with the next sync.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "One name and one number per customer (Engine v68)"),
      el("p", { class: "card-sub" },
        "A customer's name and WhatsApp number used to live in two places — on their orders and on their customer card — and could disagree. Now saving the card writes the name and number onto every one of their orders, so your labels, messages and customer list all follow; and fixing a wrong number with “Edit” on an order carries back to their card too. Leaving a box empty means “leave it as it is” — it never wipes a number your confirmations need. Anyone you renamed before today gets put right automatically the first time this version opens."),
      el("p", { class: "hint" },
        "Correcting a number brings that customer's bring-a-friend credits across with it, and renaming someone with no number on file no longer loses them.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A “No name” customer keeps the name you save (Engine v67)"),
      el("p", { class: "card-sub" },
        "When a customer reaches you without a name — a storefront order that carried none — their row in the customer book now takes the name you save on their profile. Open the person, tap “Add details”, type their name (and the pet's name, likes and so on) and save: the row, the finder and the “Hi {name}!” WhatsApp greeting all use it from then on. Before, the row only ever read the order, so an unnamed customer stayed “No name” no matter what you typed."),
      el("p", { class: "hint" },
        "Your order's own name still wins when there is one — the saved profile name only fills in for someone recorded anonymously.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Product text that translates itself into 中文 & Bahasa Malaysia (Engine v66)"),
      el("p", { class: "card-sub" },
        "When you save or publish a product, the app quietly fills the Chinese and Malay versions of its name, description, selling unit and feeding tip — machine-made from your English, free, whenever you're online. Each translated box is tagged “auto”. Type over any box and it becomes yours: your own wording is never overwritten. In Products → Edit you can also tap “Fill all 中文” or “Fill all Bahasa Malaysia”, or fill one line at a time with ↻. Blank English means no translation, and if you later change an English line, that box is re-filled to match."),
      el("p", { class: "hint" },
        "A shopper reading in that language then sees the product in their own words on your order page — a translation only ever exists because your English version does.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Products in three states: Draft, On the shop, Hidden (Engine v66)"),
      el("p", { class: "card-sub" },
        "Products now sit in three separate lists. A brand-new product starts as a Draft — fully built but not for sale until you Publish it. On the shop holds what customers can actually order. Hidden is a product you took down but want to keep (history and recipe stay). Publish a draft to start selling it; Hide any live product to pause it."),
      el("p", { class: "hint" },
        "Drafts and Hidden products never appear on your storefront and can't be ordered, so building a new recipe can't accidentally go live.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Copy the referral follow-up in your customer's language (Engine v66)"),
      el("p", { class: "card-sub" },
        "In a customer's profile, before you tap “🎉 Copy follow-up”, you can pick the message's language — English, 中文 or Bahasa Malaysia. The whole check-in, including the product's translated name and feeding tip, is written in that language, so the text you paste into WhatsApp already speaks in your customer's own words. English stays the default."),
      el("p", { class: "hint" },
        "The follow-up is the warm check-in that slides the bring-a-friend link in after a delivery.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Reviews to publish, one at a time (Engine v65)"),
      el("p", { class: "card-sub" },
        "More → Reviews now shows each review one at a time, exactly as it will look on your homepage — the ones waiting to be published first. Publish puts it up, Take down hides it, Delete removes it for good, and each action moves you on to the next one. Home and the ⭐ Reviews menu row show an “N waiting” count whenever new reviews are sitting on you."),
      el("p", { class: "hint" },
        "No autoplay on purpose: it's a deciding screen, not a slideshow — the review in front of you stays until you act on it.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "中文 / English / Bahasa Malaysia — the whole site (Engine v64)"),
      el("p", { class: "card-sub" },
        "Your homepage and ordering page now speak three languages. Tap English / 中文 / BM at the top and every word — buttons, delivery days, the order form — switches over on the spot (your phone remembers the choice). You can also give a product a Chinese or Malay shop name in Products, so the card reads 鸡肉干 or Jerky Ayam while orders still track the English name."),
      el("p", { class: "hint" },
        "Each visitor picks their own language, so one link works for every customer.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Homepage reviews as a carousel + a website credit (Engine v64)"),
      el("p", { class: "card-sub" },
        "The “What customers say” section on your homepage now swipes — readers drag left or right through the reviews you've published, or tap the dots. And if your website was made for you, Settings → Website & developer lets you name who built it: a small “Website by …” credit then shows at the bottom of the homepage and order page, and More → About gains a WhatsApp and email row to reach them."),
      el("p", { class: "hint" },
        "The same developer is who the wish list emails. Add a wish on More and it can send the whole list to them automatically — or tap “✉ Email the full list” to send it yourself.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A Customers tab with profiles & a finder (Engine v63)"),
      el("p", { class: "card-sub" },
        "Customers now has its own tab in the bottom bar, and each person can carry a small profile — their pet's name, a photo, what they like, what to avoid, and a note. Type in the finder box to narrow the list by name, number, pet's name or favourite product. Dogs and cats both fit. The Purchase Order screen moved under More to make room, and photos you pick are shrunk to a tiny thumb before saving."),
      el("p", { class: "hint" },
        "Profiles ride the same customer list on both your phones, so what you learn about a regular on one phone is there on the other.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "An always-on Upcoming holidays card (Engine v63)"),
      el("p", { class: "card-sub" },
        "On Home, the “Upcoming holidays” card now always shows: with nothing marked it explains how to add days on the Delivery calendar, and once more than three are coming up the list scrolls instead of dropping the rest."),
      el("p", { class: "hint" },
        "Before, a quiet week made the card vanish — now it's a steady reminder either way.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Engine version, wish list & change history (Engine v63)"),
      el("p", { class: "card-sub" },
        "More now shows which engine version you're on, has a wish list where you can jot ideas for the app (a tick stays ticked until you untoggle it), and links to the full change history from v54 onwards as a PDF you can read on any phone."),
      el("p", { class: "hint" },
        "Think of the wish list as your idea notebook for the software, kept with the app itself.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Amber “not sharing” strip + read-only backup View (Engine v62)"),
      el("p", { class: "card-sub" },
        "When a phone isn't on the shared cloud — shared data off, never set up, or signed out — an amber strip now shows on every screen so you always know. And each copy under Settings → Backup & safety has a View button: it opens that copy read-only (its orders, prices and stock), so you can check an old detail without moving today's data."),
      el("p", { class: "hint" },
        "Viewing a backup changes nothing — no writes, no reload — it's a window into that copy's past.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Cloud backups you can step back to (Engine v61)"),
      el("p", { class: "card-sub" },
        "Every day you open the app signed in, a full copy of your records quietly saves to your own cloud — a Daily copy the first time the app opens each day, a Weekly copy on Mondays, a Monthly copy on the 1st. It keeps the newest 7 daily, 4 weekly and 3 monthly copies. In Settings → Backup & safety you can Restore your phone back to any copy (a “Before restore” copy is saved first, so you can undo it), Download one as a file, or Delete it. Automatic copies tidy themselves up; Manual ones stay until you delete them."),
      el("p", { class: "hint" },
        "Your cloud copies sit behind the same private login as your shared records — customers never see them. Restore rewinds your phone AND the shared cloud to that copy.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Homepage reviews you approve first (Engine v60)"),
      el("p", { class: "card-sub" },
        "Your homepage can now show a “What customers say” section. Visitors leave a review — a star rating, a few words in English / 中文 / Bahasa Malaysia, and an optional photo — but nothing appears publicly until YOU tap Publish on it, in More → Reviews. New ones sit under Waiting for you; Publish puts it on the homepage, Take down hides it again, Delete removes it for good."),
      el("p", { class: "hint" },
        "Customers post into your own cloud and only your tap makes it public — the same trust step as confirming a storefront order before accepting it.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Tick a whole occasion group at once (Engine v59)"),
      el("p", { class: "card-sub" },
        "On the Delivery calendar → Mark an occasion, the import list groups the ready-made occasions — pet days, people & kindness days, and more — so you can tick a whole group in one tap, then untick any you don't want before adding them all to your calendar. A “My own day” box lets you type any occasion the list doesn't have, e.g. “Pet-treat promo day”."),
      el("p", { class: "hint" },
        "Whole-group ticking saves taps when you want most of a group; the group's master checkbox shows a dash when only some of its days are ticked.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A catalogue of occasions to add (Engine v58)"),
      el("p", { class: "card-sub" },
        "Behind “＋ Add occasion” on the calendar is now a curated list of ready-made special days — Malaysian public holidays plus fun days for pets and people (World Animal Day, National Pet Day, International Cat & Dog Day and similar) — colour-coded red for public holidays, orange for the rest, so the calendar stays easy to read."),
      el("p", { class: "hint" },
        "These are suggestions to import, never automatic — you choose which ones land on your calendar.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A note on each ingredient line (Engine v57)"),
      el("p", { class: "card-sub" },
        "In a product's recipe, every ingredient line can now carry its own short note about that ingredient for this product only — e.g. which cut or brand of chicken, or which variety of sweet potato. It's for your eyes alone: it never appears on the shop, a label, or the product cards. Because it rides on the product like the recipe does, both your phones see it."),
      el("p", { class: "hint" },
        "Sits under the “amount × price” line — the same ingredient can read differently in different products (e.g. chicken in one recipe, duck in another).")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "“Keep at least” reserve stock (Engine v56)"),
      el("p", { class: "card-sub" },
        "On the Ingredients screen, next to “On hand” there's now “Keep at least”. That's your floor — how much you want left on the shelf after a busy posting day. Your shopping list tops an ingredient back up to that level automatically, so you're never caught short. Set it once per ingredient; it syncs with the ingredient, so both your phones see the same number."),
      el("p", { class: "hint" },
        "Runs on top of the “On hand” stock number (Engine v54) — if you track what you have, the app can tell you what to re-buy.")));
}

function introCard() {
  return el("div", { class: "card" },
    el("p", { class: "card-title" }, "Your app, explained"),
    el("p", { class: "card-sub" },
      "Your bakery app and this app are twins under the hood — they share the same engine. This guide explains the engine in everyday words, so the two never feel confusing."),
    el("p", { class: "card-sub" },
      "It lives only here in Munchies Furkidz — your bakery app doesn't need it."));
}

function analogyRows(rows) {
  return rows.map(([term, meaning, analogy]) =>
    el("div", { class: "card" },
      el("p", { class: "card-title" }, term),
      el("p", { class: "card-sub" }, meaning),
      el("p", { class: "hint" }, "Analogy: " + analogy)));
}
