// views/guide.js — a plain-English guide to the shared engine, for THIS app
// only (the bakery doesn't get it). Explains, in everyday words, that munchies
// and the bakery run the same engine, which step maps to which name, and what
// lives where. Content master kept in Claude's memory; refresh here whenever an
// engine sync lands so new-version notes stay current.

import { el, button } from "../ui.js";
import { ENGINE_VERSION } from "../version.js";

// Navigate by hash so app.js isn't needed at import time.
const navigate = (hash) => { location.hash = hash; };

export function renderGuide(root, state) {
  root.replaceChildren(
    el("div", { class: "btn-row", style: "margin-bottom:10px" },
      button("← Back", () => navigate("#/more"), "ghost")),

    introCard(),

    el("h2", { class: "section" }, "One engine, two shops"),
    ...analogyRows([
      ["The engine",
        "The shared software underneath BOTH your businesses. It decides how every screen, button, order and sync works.",
        "Like the same car engine fitted under two different shop signs — one for your bakery, one for Munchies Furkidz."],
      ["Engine updates (syncing)",
        "New engine improvements are built on your bakery app first, then copied into this one, so the two always work the same way.",
        "Like perfecting a new kitchen gadget in one kitchen, then installing the same gadget in the other."],
      ["Engine version",
        "A numbered batch of improvements. Right now both apps run Engine v" + ENGINE_VERSION + ".",
        "A version sticker on the machine — check this More screen and your bakery's More screen; they should match."],
      ["Your words vs the engine's",
        "The engine keeps ONE internal name for every step. Each of your shops shows its own word on screen.",
        "One kitchen timer, two different labels stuck on it."],
    ]),

    el("h2", { class: "section" }, "Same step, different name"),
    ...analogyRows([
      ["Preparing (this app)",
        "The step where an order is being made. The bakery calls this same step “Baked” — it's the identical engine step, just named for pet treats.",
        "Two shop signs, same room behind them."],
      ["Posting day (this app)",
        "Your production days — Monday / Wednesday / Friday. The bakery says “bake day”; yours is a “posting day” because your treats are posted nationwide.",
        "Same schedule on the calendar, different name in each shop."],
      ["Post vs Collect",
        "How an order reaches the customer: Post (nationwide) with a flat fee, or Collect (local). The bakery uses “Courier / Collect”.",
        "Same two ways to hand something over, your own labels."],
    ]),

    el("h2", { class: "section" }, "What stays yours alone"),
    ...analogyRows([
      ["Your cloud cabinet",
        "Orders, products, your “On hand” stock, the postage fee you set and more sync between YOUR phones through your OWN online cabinet (Supabase). Customers never see any of it.",
        "A notebook in the sky — but each business has its OWN notebook. This app never touches your bakery's records."],
      ["Your postage fee",
        "The RM8 posting fee is quoted only by you, on your WhatsApp confirmations. It syncs between your phones — whatever you set last wins — so both quote the same figure. It is never published to the storefront: customers only hear the exact amount from you.",
        "The private price list you and your other till share — not the menu hanging in the window."],
      ["On this phone only",
        "A few things really do stay on the phone you're using: your app PIN and the cloud-login email & password you type in. Your “On hand” stock is NOT one of these, and neither is the postage fee — both sync like the rest of your records.",
        "A sticky note on the till — not copied into the sky notebook."],
      ["Your branding & prices",
        "Domain munchies.com.my, product names, prices, photos, WhatsApp/Instagram — all yours, per shop.",
        "The sign, the menu and the prices are yours; only the machinery underneath is shared."],
      ["Backup file",
        "“Backup” in Settings makes a full copy of your records to keep safe.",
        "A photocopy of the whole notebook, put away in a drawer."],
    ]),

    el("h2", { class: "section" }, "Newest built for this app alone"),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A customer can put a code in, and the order tells you what to take off (this app alone)"),
      el("p", { class: "card-sub" },
        "Until now a code could only arrive by scanning a label's square. The order page now carries a small \"Have a code?\" box at the top, on every visit, so a customer who was told the code at the counter — or who copied the letters off a card by hand — can type it in themselves. Typing a code replaces whatever the link brought, and clearing the box and pressing Apply puts the label's own code back. A code the app never printed is still quietly ignored, so a made-up code never lands in your books as a label that never existed."),
      el("p", { class: "card-sub" },
        "Under the offer the page now says what will happen to it: \"We'll take this off when we confirm on WhatsApp — the total shown is before the discount.\" If the basket is under the code's minimum it says how much more is needed instead — \"Add RM8.00 more to use it.\" The total never moves, and that is the point: an order keeps the price it was sold at, so a discount quietly taken off on the page would rewrite what you actually earned — and \"new customers only\" cannot be checked from the page at all, because that needs your whole order book."),
      el("p", { class: "card-sub" },
        "So your app does the telling. An order that came in on a code now carries a 🎟 line on its row and in its Edit box: the code, the shop or product it was for, what it promised, and \"take it off when you confirm.\" Two warnings appear when they apply — that the offer is for new customers only and this person has bought from you before, or that the order is under the code's minimum spend, naming both figures. The line never goes blank: a code you have since retired, or even deleted, is still named, because the order records what the customer came in on."),
      el("p", { class: "hint" },
        "The line states; it never subtracts — nothing in your books changes. Money, Profit, the WhatsApp confirmation and the customer's track page all keep reading the price the order was sold at, and what you take off at confirmation stays your decision, exactly how a bring-a-friend credit already works. One fix came with it: the offer shown on the page now honours its own Ends date, so a label whose offer has run out stops showing it. The counts on Shops & codes now also include orders where a code was typed rather than scanned — which is right, since it is the same printed label.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "One label can say its own words on the page (this app alone)"),
      el("p", { class: "card-sub" },
        "Every label used to open the same page, so every card a customer scanned read the same heading and the same sentence under it. Now one label may carry its own. Open a code, tap What this label says on the page, type a heading and a paragraph, then press Fill 中文 / BM — and only that label's page reads that way. So one promotion card can shout its own offer while a shop's sample card keeps the shop's words."),
      el("p", { class: "card-sub" },
        "Leave a box empty and the shared page's line is what the customer sees. The greyed text in an empty box is exactly the line they would get, so a label that says nothing for itself changes nothing at all — and clearing a box puts it back to the shared page's words."),
      el("p", { class: "card-sub" },
        "Every translated box carries a small 中文 or BM tag beside it so you can always see which language you are typing into — on a label, the greyed line inside a box is the shared page's words rather than the language's name, and two boxes would otherwise both read as the same English."),
      el("p", { class: "hint" },
        "One line per language, not per box: if you write this label's heading in English and leave the 中文 box alone, a Chinese-reading customer gets the shared page's 中文 line for that heading. Press Fill 中文 / BM after you change the English and the boxes you have not touched are translated again — a line you typed yourself is left exactly as you wrote it.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A printed label that carries a code, and the page it opens (this app alone)"),
      el("p", { class: "card-sub" },
        "More → 🏪 Shops & codes is a new screen where you make a code for anything you print: a pet shop's sample card, a short promotion (say 10% off one product until 30 Sep, new customers only), a bring-a-friend card, or a plain card that just says hello. Each code gets its own square — a QR you can download as a picture or print as a sheet of labels — and the same code's short letters, like K3X9, are printed small beside the square so you can tell two labels apart by eye. When a customer scans the square, the page opens with the label's code in it, states what that label offers, asks whether the treat is for a dog or a cat, and sends them on to your shop with the label still attached."),
      el("p", { class: "card-sub" },
        "One code is one printed label, and a code can carry more than a promotion — the same mechanism names a product, a shop, or a friend who sent them. Every opening of a label's page is counted for you (and the dog-or-cat answer with it); those counts sit in your own cloud behind your login, so only you can read them, and a customer can only add one. The screen also tells you what a label has brought in, so you can see which shop's cards are working."),
      el("p", { class: "hint" },
        "This was built here first, so the engine number does not move — both your apps stay on the same number, and your bakery does not have this screen. The words on the customer's page are yours to write on the Shops & codes screen (English, 中文 and Bahasa Malaysia) — on the shared page every label opens, on a page of your own that a promotion's labels share, and on any single label that needs its own — so you can change what a scanned label says without changing the app.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Hold a phone up to a printed label to look it up (this app alone)"),
      el("p", { class: "card-sub" },
        "The 📷 Scan a label button on the Shops & codes screen opens your camera so you can point it at a printed square and see at once which code it is, what it offers and how many orders it has brought. Typing the short letters works everywhere as well — it sits right there beside the camera button, never a fallback you have to go looking for."),
      el("p", { class: "hint" },
        "The camera works on Android and on a computer. An iPhone's Safari cannot read a QR inside a web page — that is Apple's rule, not this app's — so on your own phone, type the code from the label. Nothing about a code needs the camera: a customer's ordinary phone camera reads the square fine, because that happens in their camera app, not in the page.")),

    el("h2", { class: "section" }, "Newest in the engine"),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Your landing pages: write a promotion's words once, and every label on it follows (this app alone)"),
      el("p", { class: "card-sub" },
        "Under More → 🏪 Shops & codes there is now a \"Your pages\" card, and a \"Landing page\" dropdown on every label. A page is a set of words for one activity — \"Sample card\", \"Raya promo 2026\", \"Clearance\" — so a promotion running on a dozen printed cards is written once and every card on it follows. Pick which page a label opens from the dropdown when you make or edit that label; leave it on the first choice, the shared page, and the label reads the words you already had. A label can still say a line of its own: type over any box on the label and that line wins for that label alone, and anything you leave blank comes from its page."),
      el("p", { class: "hint" },
        "A page reads out the same two lines as the shared page — a heading and a paragraph — each in English, 中文 and Bahasa Malaysia, and each resolved on its own, so a page that only has English typed still shows the shared page's 中文 rather than a blank. Because every printed label only carries its short code, the words on a page are read live at scan time: edit \"Raya promo 2026\" and the cards already in customers' hands say the new words, with no reprint. Deleting a page does not lose anything — the labels sitting on it go back to reading the shared page, and their own typed lines stay. The confirm box tells you how many labels that is before it acts. This was built here first, so the engine number does not move: both your apps stay on the same number, and your bakery does not have this card.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Unavailable: sold out and not-sold-that-day are one section, and a product is named by the days it IS sold (Engine v123)"),
      el("p", { class: "card-sub" },
        "The middle section of the product list is now called Unavailable, and it holds both kinds together: a product that has sold out for the day you are adding to, and a product the shop does not sell on that day at all. That second kind is no longer given a count for a day it was never on — it is named by the days it IS sold, so a weekend-only treat on a Wednesday reads \"Chicken Jerky 100g — only Sat & Sun\". The three headings now read On the shop, Unavailable, Taken down."),
      el("p", { class: "hint" },
        "They are one section because they are the same thing to you: an active product you can still choose. You make to a plan of your own — as you put it, every day the kitchen may make 12, ordering closes the day before at 6pm, and the 12 are not necessarily sold off, so some go to a walk-in or into the fridge. The picker is a guide while you sell, never a gate: nothing is blocked, and the order-by deadline you set on a product is deliberately not counted, because that deadline stops a stranger ordering — it says nothing about what you may sell by hand.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The three kinds get their own headings inside the open list (Engine v122)"),
      el("p", { class: "card-sub" },
        "Adding items to an order — in ＋ New order and in Edit — the product list now comes in three labelled sections instead of one long run of names: On the shop first, then the ones you cannot sell for that day, then Taken down. The headings appear on every phone, because they are part of the list itself. On a phone with a very recent system — a new iPhone or a recent Android — each section is also tinted inside the open list: green for on the shop, amber for unavailable, grey for taken down, so the menu reads as three blocks you can tell apart without reading a word."),
      el("p", { class: "hint" },
        "The open list is drawn by your phone itself, and an older phone will not let a page colour it. On those you get the same three headings in the same order, and the closed box still wears the colour of whatever it holds — you lose the section tint and nothing else. This replaces what v121 did: v121 put the colour on the closed box alone, because the open list could not be reached. Newer phones can be reached, so the list carries the colour too.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The product list is sorted into three kinds, and the closed box wears that colour (Engine v121)"),
      el("p", { class: "card-sub" },
        "In ＋ New order and in Edit, the product list is now sorted into the three kinds you already know, in the order you would reach for them: what is On the shop first, then anything that has sold out for the day you are adding to, then whatever you have taken down (still marked \"(hidden)\"). A product still in Draft stays out of these lists entirely, as it always has. The closed box wears the colour of whatever is picked — green for on the shop, amber for sold out, grey for taken down — so on an order with several lines one glance down the list tells you which lines need a second look, without reading each one."),
      el("p", { class: "hint" },
        "The colour sits on the box you see while the list is shut, which is where you read it anyway. The list itself is otherwise unchanged: the same products, the same \"(hidden)\" marker, the same \"12 left\" count.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "One customer is one row, and two rows can be joined by hand (Engine v120)"),
      el("p", { class: "card-sub" },
        "A customer's number is now read by its digits, so 012-345 6789, +60 12-345 6789 and 60123456789 are one person instead of three. A number written with a + in front used to look like a different customer, so the same person could appear twice in the Customers list — your messages always went to the right person; only the list disagreed. A one-time tidy runs the first time you open the app after updating: it joins anyone who was split this way, carrying their pet's name and photo, what they like and avoid, and their note across to the one that remains. There is nothing to do — you simply find one row where there were two."),
      el("p", { class: "hint" },
        "New: Join with another customer, under the number on a customer's history. Tap it, pick the duplicate from the list, and confirm. Reach for it when two rows are split for some other reason — a misspelt name with no number beside it, say — which the tidy above cannot guess at. It moves the other person's orders under the name and number of the customer you were looking at, so open the row you want to KEEP. This one cannot be undone inside the app; take a cloud backup first from More → Backups, which is the way back, and the confirm box says so before it acts. Update both phones — a phone still on v119 can save a number the old way.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Start typing a name and the people you have already served appear (Engine v119)"),
      el("p", { class: "card-sub" },
        "In both order forms — the ＋ New order card and the Edit pop-up — typing two letters of a customer's name offers a short list right under the name box. Each row shows their number, how many orders you have taken from them, and what they buy most, like \"012-345 6789 · 5 orders · usually Chicken Jerky 100g\". Tap the right person and the name and the number both go in; the posting day, the items and collect-or-post stay yours to set."),
      el("p", { class: "hint" },
        "One letter on its own is not a search — it would offer you half your customers — and a name you have never served offers nothing at all. Typing a number without its dashes finds it too, so \"012345\" works the way \"012-345\" does. It draws on the orders already in the app, so a brand-new setup has nothing to offer until your first order is saved. And on the Edit form, saving a changed name has always carried that name to every other order belonging to that person (the one-saved-name rule from v68) — that has not changed, but picking a name is now much easier than typing one, so it is easier to do by accident.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The Paid step keeps its place and wears an X until the money is in (Engine v118)"),
      el("p", { class: "card-sub" },
        "Some regulars pay when they pick up — cash or TNG handed over at the counter — so their order goes from Confirmed straight on to Preparing and never passes through the Paid step at all. v117 simply left that step off those orders' map. You asked for the step to keep its place instead: every order now shows all six steps, and a step where the money has not been recorded yet wears an amber ✕ rather than a green tick."),
      el("p", { class: "hint" },
        "It becomes the ordinary green tick the moment you record the money — the Paid · Cash or Paid · TNG button, or Paid by in the Note / tracking / payment pop-up. The point of keeping the step rather than dropping it: every order's map reads the same way, six steps in the same places, so the one step still owing is plain to see on your row and on the customer's own track page, which draws the same six steps.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Paid · Cash and Paid · TNG stay on at every later stage (Engine v117)"),
      el("p", { class: "card-sub" },
        "A regular who pays at pickup hands the money over long after the order has moved on — often on the day they collect. The two Paid buttons used to appear only while the order sat on the Paid stage, so by the time the money changed hands they had gone, and there was no way to record it. They now stay on from Paid onwards — Paid, Preparing, Packed, and the last step — until the money is recorded."),
      el("p", { class: "hint" },
        "Taking the money at the counter records it where the order already is: the order stays Packed rather than being dragged back a step, it is stamped with the day the money landed (which is the day the Money screen counts as that money coming in), and the row then shows how it was paid instead of the buttons. An order that has not reached the money stage yet is left alone, as before.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Day one: tell the app what you are starting with (Engine v116)"),
      el("p", { class: "card-sub" },
        "More → Money has a new Day one line with a Set button. It is the form for the day your books begin: how much cash is in your tin, how much is on your phone (TNG), the day your books start, and a box for each ingredient — the amount of it you already have on the shelf. Fill in what you have and leave the rest blank; anything you leave empty is left exactly as it is."),
      el("p", { class: "hint" },
        "The cash and the TNG are written as ordinary money-in lines, exactly as if you had typed them with Put money in, so they count into the Cash in and TNG in rows you check your purse against. Each ingredient box sets that ingredient's On hand, which is what your shopping lists subtract — so your first list buys only what you are short of. Every box is checked before anything is written, so a slip halfway down the form does not leave half an opening balance saved, and a day you type outside the stretch on screen will not show in that stretch's Net.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The month arrows on Profit work both ways again (Engine v115)"),
      el("p", { class: "card-sub" },
        "Profit opens on this month, where the forward arrow is correctly switched off because there are no numbers after today. Press back one month and the forward arrow stayed switched off too, so the only way to return was to leave the screen and open it again — one-way traffic through the months."),
      el("p", { class: "hint" },
        "The arrow's state was worked out once, when you opened the screen, and then reused on every step, so it kept answering for the month you started on rather than the month you were looking at. It is worked out fresh on every step now, so both arrows move through the months you have and the forward one switches off again only when you are back on this month. The other calendars — Orders, Delivery dates, the date pickers — were never affected; they recompute their arrows each time they draw.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Every spending line in Profit opens now, and they're easy to tap (Engine v114)"),
      el("p", { class: "card-sub" },
        "On More → Profit, the lines that opened their journal were the ones with money in them. A line reading 0.00 was deliberately left dead because there was no journal behind it — but it looked exactly like a live one, so in a month where most categories sit at 0.00 nearly every line you tapped did nothing. Every spending line opens now: Packaging, Utilities, Delivery & fuel, the categories you have added, and Total expenses. An empty one opens and says so in words — \"Nothing recorded under Utilities in September 2026\" — with In / Out / Net at zero."),
      el("p", { class: "hint" },
        "Two more things came with it. The tappable rows were only 17 pixels tall — a small target for a finger, and easy to land in the gap between two lines and hit nothing; rows you can tap anywhere in the app (the Profit statement, the Money screen's cash rows, the Books list) are 36 pixels now, comfortably thumb-sized. And the Total expenses journal used to read \"2 Sep · boxes · Cash\" with no way to tell what \"boxes\" was for — it names the category now (\"2 Sep · Packaging — boxes · Cash\"), while a single category's journal still reads short, since its title already says which one it is. The statement's own totals — Sales, Cost of sales, Gross profit, Net profit — stay figures rather than doors.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Every way you pay has a book you can always open (Engine v113)"),
      el("p", { class: "card-sub" },
        "Under the two money cards on More → Money there is a new Books line. Press Open and it lists every way you pay — Cash, TNG, Loan, a personal pocket you have added, and anything you add later — each with what moved by it in the stretch on screen, and each opening into its own book right under the line you tapped, so the list stays in front of you and you can step from one book to the next."),
      el("p", { class: "hint" },
        "The reason it was needed: the journal rows live on the money card, and that card only draws a pocket's row when that pocket moved money in the stretch you are looking at — and it opens on Today. So a pocket that paid for something last week had no row today, and no way into its book at all. The four Cash and TNG rows were never affected. A way of paying you have since renamed or deleted still gets a line, because its money is still in the books — and every figure in the list comes off the Money screen's own rows, so the list and those totals cannot drift apart.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Pay a personal pocket back out of the till in one go (Engine v112)"),
      el("p", { class: "card-sub" },
        "On More → Money, beside Put money in, there is now Pay back a pocket. When a pocket of yours — a personal pocket, a loan — has paid for something, its line on the Money screen reads minus the amount, which means the till owes it. Open the form and it comes up already on the pocket that is owed, with the amount filled in. Say whether the money came out of Cash or TNG, check the day, and press Pay back."),
      el("p", { class: "hint" },
        "It writes both halves at once, which is the whole point: the till goes down by that amount — Cash out, the Net, and the Cash journal with your note — and the pocket's line returns to zero. One pocket can be settled without touching another. Because it is your own money going back to you, the till's side is recorded as a withdrawal, so it is never a cost and your profit does not move, and the pocket's own list now says Paid back by the till rather than From my pocket. Part payment is fine: pay RM 25 of RM 40 and the pocket reads 15 short afterwards. This same version fixed the row of categories on the expense form, which was running off the side of a phone screen and hiding the last few categories and the ＋ New category chip: the pills wrap onto as many lines as they need now, and so do the ways-to-pay row and the new pay-back form.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Tap a line on the books and see what made it up (Engine v111)"),
      el("p", { class: "card-sub" },
        "Every figure on the books is a door now. On More → Profit the running-cost lines — Packaging, Utilities, Delivery & fuel — are tappable, and so is Total expenses: tap one and its journal for the month opens on the same screen, oldest first, each line reading the day, what it was for and how it was paid, and ending on the total the statement itself shows. A line with nothing in it that month is not tappable, because there is nothing behind it. On More → Money the single Paid by loan / other row is replaced by one line for each way of paying that is not cash or TNG, each with its own journal behind it."),
      el("p", { class: "hint" },
        "The lines are read off your own transactions rather than a fixed list, so a way of paying you add tomorrow needs nothing from me — record one payment with it and it has a line and a book. A method you have since renamed keeps a line for the name its older rows were written with, because those rows are still in the books and a figure you cannot open is a figure you have to take on faith. Cash in, TNG in, Cash out, TNG out and the Net are exactly as they were, and none of the other ways of paying is in the net — that money never came out of your purse.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "An ingredient you never buy can be marked as one (Engine v110)"),
      el("p", { class: "card-sub" },
        "Open More → Ingredients, tap Edit on an ingredient, and above the cost there is a new switch: Not something I buy — it only ever costs. It still counts in a recipe's cost, but it never appears on a shopping list or a purchase order. Turn it on for Labour, Electricity, Gas, your own time."),
      el("p", { class: "hint" },
        "Its card stops showing On hand and Keep-at-least and says Not bought — a cost in your recipes, never on a shopping list. Every shopping list leaves it out and says so at the foot, so it reads as deliberate rather than as something the app forgot. The recipe cost is untouched: Labour at RM 8 an hour for 15 minutes still adds RM 2.00 to a product's cost, and that runs on into the Profit screen's cost of sales. Switching it off removes the mark entirely, so nothing that exists today changes unless you turn it on. One warning that comes with it: if you mark Labour as not-bought because it is your own unpaid time, it is already inside your products' cost through the recipe, so do not also record it as a Salary expense — or the same hours are counted twice.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A journal for each way the money moves (Engine v109)"),
      el("p", { class: "card-sub" },
        "On More → Money, Cash in, TNG in, Cash out, TNG out and the loan line can be tapped. Each opens that method's book for the stretch you are looking at: every order paid that way with its code and customer, everything you spent out of it with its note, anything of your own you put in — in date order, ending on In / Out / Net and a line saying what that is meant to be (your purse, your phone, or money that never went near either)."),
      el("p", { class: "hint" },
        "A bug was fixed in the same version and it is worth knowing about. Every order you had marked Paid · TNG since v106 was landing in Paid, no method instead of the TNG column, because the app was checking for the old spelling (tng) while the paid buttons write the list's own label (TNG). So the TNG in figure read RM 0.00 with the money sitting in your phone, and the same money showed as unaccounted for. If your TNG column has looked wrong since v106, that was it.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The categories and ways to pay moved to where you work (Engine v108)"),
      el("p", { class: "card-sub" },
        "The two lists are no longer tucked away in a Settings card, where you could not find them. They are a line under the money lists on More → Money — Categories & ways to pay · 11 categories · Cash, TNG, Loan — with an Edit beside it. Tap Edit and every category and every way of paying opens, each line saying edit; tap a line and it turns into the form in place, so you can rename it, change what kind it is, or delete it with the rest of the list still in front of you."),
      el("p", { class: "hint" },
        "Renaming moves what you have already recorded under it, so a slip of the thumb cannot split your history into Packaging and Packing. And the ＋ chips now sit where you are working: the Add an expense form and Put money in each end their row of pills with ＋ New category and ＋ New way to pay, which opens the same small form in place and keeps the amount and the note you had already typed. These forms expand where they are rather than opening a window of their own, for the same reason the date field does — the app has one pop-up layer, and a second window would wipe out the form underneath it.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The item line on an order reads properly again (Engine v107)"),
      el("p", { class: "card-sub" },
        "When the selling price joined the item line in v101 it took most of the row: measured on a 375-pixel phone, the price box was 183 pixels wide and the product dropdown was squeezed to 2, so the name of what you had picked was pushed onto a line of its own and could not be read. Each item line is two clean lines now — the product across the top at full width, and its controls underneath: how many, the selling price on the right, and the ✕ to remove."),
      el("p", { class: "hint" },
        "The same shape is used in the ＋ New order card and in the Edit pop-up, since both are the same row.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A note on every transaction, and two lists you shape yourself (Engine v106)"),
      el("p", { class: "card-sub" },
        "Add an expense now takes a note, the way Put money in already did (Mydin run, 2 boxes), and both lists on the Money screen show it beside the amount, so a row reads as what it was rather than just a figure. The categories are yours: each shows what it means to the accounts — ingredients, a running cost, or your own money — you can delete one with its ✕, and you can add your own, Pet expo or SSM licence, choosing which of the three it is. The ways to pay are yours too: Cash, TNG and Loan to start with, and you can add a Bank OD or a cheque."),
      el("p", { class: "hint" },
        "Deleting a category never touches what you have already recorded — those rows keep their label and still count, printed at the end of the statement's cost list rather than dropped. One thing follows from having your own ways to pay: money that never came out of your purse — a loan, an overdraft — no longer sits in the net. The Money screen leaves it out of the cash figures and names it on its own line with a sentence saying why, so Net means exactly what it says: what should be in your purse and on your phone.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The books: a profit and loss account, a month at a time (Engine v105)"),
      el("p", { class: "card-sub" },
        "A new screen, More → Profit. Month by month, with arrows either side, it reads down like a set of accounts: Sales, Cost of sales, Gross profit, the running costs one line each, Total expenses and Net profit, with the gross margin beside the order count. Then, kept apart from all of it, your own money: capital you put in, drawings you took out, and what is left in the business."),
      el("p", { class: "hint" },
        "The one rule that makes it accounting rather than a cash total: ingredient cost is what the making cost, taken from your recipes as the treats sell — not the packs you bought. A shopping run is money out on the Money screen and stock on your shelf, and it becomes a cost of sales here as the treats made from it go out, so a big stock-up week stops looking like a loss and nothing is counted twice. Your own money is neither income nor a cost: what you put in is capital, what you take out is drawings, and neither changes profit — though a real salary you pay yourself, under Salary (you) with EPF / SOCSO as its own category, does count as a running cost. Two things it will not pretend to know: your own unpaid hours are not costed, so if your time is worth paying, pay yourself a salary and they become one; and a product whose recipe prices to nothing is counted as costing nothing, with the screen telling you how many lines that was.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Money you put in yourself, and taking it back out (Engine v104)"),
      el("p", { class: "card-sub" },
        "Some spending happens before any order money arrives — a packet of meat paid from your own purse, a float of change for the day — and there was nowhere to put it. More → Money now has a Put money in button beside Add an expense: how much, the day you put it in, cash or TNG, and a short line saying what it was for. It counts into the Cash in and TNG in rows, because your own money really is in your purse and those rows are what you check the purse against, and one line underneath says how much of the money in was yours."),
      el("p", { class: "hint" },
        "The entry is listed in its own Money in card, so you can see where it came from and take it off again. And Add an expense has a new category, My own withdrawal — money you take back for yourself rather than a cost of making. It leaves through the same money-out list as everything else, so the net, the day lines and your backups count it with no new machinery.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Money out: what you spend, beside what you take in (Engine v103)"),
      el("p", { class: "card-sub" },
        "v101 gave you the money coming in; spending had nowhere to go. Now, when you tap Bought on a saved shopping list and the packs land on your stock, a small box asks What did you pay? — pre-filled with the list's own total and Cash or TNG beside it. Accept the guess with one tap or type what the receipt really said; Skip the money adds the stock and records nothing, exactly as before."),
      el("p", { class: "hint" },
        "Everything a purchase order never sees goes in by hand: More → Money carries an Add an expense form for packaging, delivery and fuel, utilities, equipment or a market top-up, each with the day you paid it, so a receipt found in your bag later still counts on the right day. The Money screen adds it up both ways — Cash in, TNG in, Cash out, TNG out and Net, what should be in your purse and on your phone for Today / This week / This month — with that stretch's spending listed underneath. What is still to collect stays out of the net: it is money owed, not money held. One small fix came with it — a payment taken just after midnight was being counted on the day before, because the app read the date off the stamp in UTC; it counts on your own day now.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "You can drag across the calendar to pick a run of delivery dates (Engine v102)"),
      el("p", { class: "card-sub" },
        "One small change on More → Delivery dates. That calendar now works the way a product's availability calendar does: drag your finger across the days and the whole run fills in as you go, then Add selected puts them on the calendar. A single tap still picks one day, or puts it back — and a day that is already a delivery date is left alone by a drag, because it comes off by tapping it, the way it went on."),
      el("p", { class: "hint" },
        "That makes four ways in: tap the dates, drag a run, tap a weekday letter for every one of that day in the month, or press Generate the next dates from your Settings pattern. One thing I deliberately did not copy across from the product calendar: the From / To boxes. On a product those two boxes say a season — a sell period really does have two ends — but a delivery date is one day, not a stretch, so the boxes would only ever have been a slower way to do what dragging now does.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A price you can change on an order, and cash or TNG written down when it lands (Engine v101)"),
      el("p", { class: "card-sub" },
        "Every item line on the ＋ New order form and in the Edit pop-up now carries its selling price. It opens on what the product costs; type over it and THAT order is sold at your price — the confirmation, the payment and pickup reminders, the receipt, the customer's track page and every money number in the app follow it. Your menu price is untouched, and a price you change on the menu next week never rewrites a sale already made. Leave it blank and it means whatever the product costs, exactly as before. Both forms also add the items up as you go."),
      el("p", { class: "hint" },
        "The Paid button is now Paid · Cash and Paid · TNG — one tap each — and the order remembers which, and when, and shows it beside its status. The box beside Edit (now Note / tracking / payment) carries a Paid by dropdown too, for an order you marked paid before you could tell, or one to correct later. None of this reaches the customer: their page just says Paid. To check the day against your cash and your phone, the delivery day's own header on Orders carries a short till — \"Cash RM 95 · TNG RM 120 · 1 to collect\" — and More → Money is a screen of its own with Today / This week / This month: cash collected, TNG collected, paid with no method recorded, and what is still to collect with the number of orders. Money that landed is counted on the day it LANDED, so a transfer that comes in today counts today even if that order goes out on Friday; money still to collect is counted on the delivery day, because that is the day you hand it over.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Making your delivery dates for a weekday is one tap again (Engine v100)"),
      el("p", { class: "card-sub" },
        "You found the function missing: to add your delivery dates for, say, every Monday, you had to tap each Monday by hand. Nothing had been removed — the app's only \"do the dates for me\" button lived on Home, inside the \"No delivery dates yet\" message. That message shows only while you have no upcoming dates, and pressing the button creates the very dates that hide it, so it was a one-shot button that took itself off the page the moment it worked. Once you had dates — which is every day since your first week — it was never there again."),
      el("p", { class: "hint" },
        "Now there are three ways in on More → Delivery dates. Tap dates and Add selected, as before. Or tap a weekday letter: tap M and every Monday in the month shown is picked for you, tap it again to put them back, and the letter underlines solid once that whole weekday is picked. Or press Generate the next dates, which is always there, follows the delivery days in your Settings, and adds the next six dates that are not on the calendar yet — moving the calendar to the month they start in, so you can see what it just did. One wrong line got fixed alongside it: Home's \"no dates yet\" message used to say \"the next Mon/Wed/Fri dates\" whatever your delivery days really were, and it names your own days now.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The customer can tap Next available and be given that day (Engine v99)"),
      el("p", { class: "card-sub" },
        "A product you keep on the shop, on a day it cannot be ordered, tells the customer when it can be had — \"Next available: Sat 19 Sep\". Until now they had to go and find that date on the calendar themselves. The line is a control now: tapping it takes that posting day, so the product in front of them can be ordered straight away, and the page moves up to the calendar where the chosen day is written out in words. It keeps its gentle pulse, and wears a small arrow so it reads as something to tap."),
      el("p", { class: "hint" },
        "The one time it does not take the day: if the customer already has something in their basket, the line stays a plain label and tapping it answers instead — \"Your basket is for Fri, 18 Sep. To order for another day, choose it on the calendar above.\" Taking a day then would silently move their whole order to a new date, and drop anything that does not fit there, which is not something a tap on a product line should ever do. Changing the day is what the calendar is for.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "One label for the last step, and a Note / tracking button on every order (Engine v98)"),
      el("p", { class: "card-sub" },
        "Two small changes on the Orders screen. First, the last step of an order now reads Collected / Posted everywhere it is named — the row's status list, the row's own journey map, the day's status filter, and the map on the customer's track page (in all three languages). v97 named that step per order — Collected on one the customer fetches, Posted on one you mail — and you asked for the pair itself instead. Nothing about the step's behaviour changed, and every order already sitting there keeps its place."),
      el("p", { class: "hint" },
        "Second, beside Edit every order now carries a Note / tracking button. It opens a small box with exactly two fields — the order's Note and the Courier tracking number — and a Save. Send, and the note lands on the order while the tracking number also goes onto the customer's track card and into the posted message. Edit still opens the full form whenever you need it. Which message a row offers is still decided by how the order leaves: a post order shows Send posted message, a Collect order its Send pickup reminder.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The last step is named for how the order leaves, and a posted order can carry its tracking number (Engine v97)"),
      el("p", { class: "card-sub" },
        "The final step used to say Delivered for everything. It is now named for what actually happened — Collected on an order the customer fetches from you, Posted on one you mail — everywhere the status is named: the row's status list, the row's own journey map, the day's status filter, and the map the customer sees on their track page (in all three languages). Nothing about the step's behaviour changed, and every order already sitting at that step keeps its place."),
      el("p", { class: "hint" },
        "A post order also carries the courier's number. Type it in the order's Courier tracking number box, press Send posted message, and WhatsApp opens with the message already drafted — the order code, what was sent, and the tracking number. The number is published with the order, so the customer's track page shows it on its own line under the delivery details: they can read it to the courier without messaging you. A Collect order shows no such line, and keeps its Send pickup reminder.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Set day's availability now shows how the day adds up (Engine v96)"),
      el("p", { class: "card-sub" },
        "The pop-up you use to set a day's numbers used to show you the rows and nothing else — no way to see where the day's total came from, and a product you do not sell that day sat in the list looking as if it were part of it. Under the rows it now ends with a How the day adds up section: one line per product on sale that day with what it contributes, then a total line — the same number the order page uses for that day. Type a + or a − and the lines and the total move as you type."),
      el("p", { class: "hint" },
        "Underneath, it names what it left out (Not counted: Saturday loaf — not sold on this day, so no order can go on them here) and says what is already booked, so you can read how much the day can still take. A product not sold that day keeps its row so you can still set its numbers; it simply does not enter the total.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A day's total now counts only what you sell that day (Engine v95)"),
      el("p", { class: "card-sub" },
        "The x/y on a day — the chip beside the date on Orders, the same number on the day in the month calendar, and the dials on Home — was adding up the daily limit of every product on your menu, whether or not that product can be ordered on the day you were looking at. So a day with one product on it (a limit of 12, say) still read 1/42: thirty of those units were limits belonging to products that could never take an order that day. Now only the products on sale that day count, and the same day reads 1/12 — what that day can really take."),
      el("p", { class: "hint" },
        "Products with no sell-day marks are unchanged (they sell every day, so they always count), and a day where nothing on sale has a daily limit falls back to the default capacity in Settings exactly as before — it does not drop to 0, which would make the app call the day Sold out. One knock-on worth knowing: this is the same number your app tells the order page about a day, so a day now turns FULL the moment every unit you are actually selling that day is booked, rather than at some larger number padded out by products that were never on sale. That was always the intent — it now happens at the right moment instead of late.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "One small wording change on the customer's card (Engine v94)"),
      el("p", { class: "card-sub" },
        "On a product you keep on the shop, the greyed line saying why it cannot be ordered today now reads Only available on Mon. where it read Only sold on Mon. Wording only — nothing behaves differently. The old wording was the seller's voice on a customer's card, and available is what the rest of that same card already says (Only available for posting from 19 Sep)."),
      el("p", { class: "hint" },
        "The Chinese and Bahasa Malaysia say the same thing as before, in their own words.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The track link lands on the track card, and lights it (Engine v93)"),
      el("p", { class: "card-sub" },
        "The WhatsApp confirmation you send a customer carries a \"Track your order\" link. Tapping it opens your shop page and looks the order up — but the page used to open at the very top, with the order card sitting somewhere below the fold, so the customer had to scroll and hunt for the very thing they had just tapped. Now the page goes straight to the card and the card is lit, so their order is the first thing under their eye."),
      el("p", { class: "hint" },
        "The glow goes when their finger (or mouse) actually reaches the card — never on a timer, because a fixed moment can pass while their eye is still travelling down the page. This is the same never-miss rule your own app uses when you tap an order in New Orders. It only happens for a page opened by that link: a customer who just opens your shop gets no glow and the page stays where it opened. On a phone with Reduce Motion on, the card is simply lit steadily instead of pulsing.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The New product card folds away (Engine v92)"),
      el("p", { class: "card-sub" },
        "The add-a-product card used to sit open at the top of the Products screen, and open it is a long form — it pushed your three lists (On the shop, Draft, Hidden) right off the bottom, so every look at what you sell began with a scroll past a form you were not filling in. It now arrives folded to one line reading ＋ New product. Tap it to open the form; tap the title again, or anywhere else on the screen, to fold it away."),
      el("p", { class: "hint" },
        "It stays open after you add a product, so you can type the next one straight away, and starts folded again the next time you come to the screen. Nothing about adding a product changed — the form inside is exactly as it was.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The Orders calendar answers a tap on a day you don't post (Engine v91)"),
      el("p", { class: "card-sub" },
        "The month calendar at the top of Orders rings your posting days in green with how booked each one is, and draws every other day plain. A plain day used to do nothing at all when tapped, which left you guessing at the reason. Now a warm line appears under the grid naming the day and saying it is not a delivery day, and that delivery days are added in More → Delivery dates. A holiday you marked says its usual name at the same time, so a marked day that is not a delivery day now tells you both what it is and why no order can go on it."),
      el("p", { class: "hint" },
        "Orders can still only be put on a posting day — the tap creates nothing and orders nothing, it just says so now. A plain day already gone stays silent: there is nothing left to add to it. The same answer comes from every calendar in the app that offers only your posting days: the one at the top of Orders, the picker inside ＋ New order, and the Delivery day picker in an order's Edit pop-up.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A product can stay on the shop on a day it can't be ordered (Engine v90)"),
      el("p", { class: "card-sub" },
        "A product's Availability card now opens with a switch at the very top, above the sell-day calendar: keep it on the shop when it can't be ordered. It is for the two or three hot items customers come back looking for — if one is not listed they wonder whether you still make it. Left off, everything behaves exactly as it does today, and no product you already have carries the setting."),
      el("p", { class: "hint" },
        "Switched on, the card stays on a day it is not sold instead of vanishing: greyed, stamped Unavailable, with the reason it already writes (\"Only sold on Mon\") and one more line — the next date it can be ordered, with how many are left that day when a daily limit is set. A day it has simply sold out keeps its Sold out stamp and gains the same line. Nothing on a greyed card can be ordered. The card's own title says \"· kept on the shop\" while the card is closed, so you can read the state without opening it.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The Delivery Dates screen is just the calendar now, with the past dates folded away (Engine v89)"),
      el("p", { class: "card-sub" },
        "Tapping a date that is already on the calendar now takes it back off — the same tap that put it there undoes it, so the calendar is the one place you both add and remove posting dates. If that day already has an order on it the app asks first, because that is the one removal worth a second look; a day with nothing on it just goes. The date is all that is ever removed — the orders stay in your history either way."),
      el("p", { class: "hint" },
        "The list of dates still to come is gone: the calendar already draws every one of them as a green tick and now lets you take any of them back, so the list was repeating what was in front of you. That is most of why this screen reads so much lighter. Dates already past now sit together under a Past dates heading that starts folded — every one of them, where the old list showed only the ten most recent.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The holiday tint sits on the dates at Orders, and a computer names a day just by pointing at it (Engine v88)"),
      el("p", { class: "card-sub" },
        "On the Orders screen each posting day carries its booking count, and that count sat under the date number — which pushed the number above the middle of its row, so the holiday wash sat lower than the dates it was meant to be tinting, and the dates did not line up with each other. The count now sits at the foot of the day, every date sits on one line, and the tint runs through that line. Nothing else about that calendar moved."),
      el("p", { class: "hint" },
        "And on a computer, resting the mouse pointer on a marked day now shows its name on its own, exactly as the customer's page does. It is deliberately only for a pointer that can hover: a phone keeps the tap, so a finger sweeping across a run of days on the Availability or Delivery Dates calendars never drags a bubble along with it.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Tap a marked day and it tells you its name — on every calendar (Engine v87)"),
      el("p", { class: "card-sub" },
        "Engine v85 drew your marks on all five of the app's month calendars, but only as colour — a wash and a band, with nothing to say which holiday it was. Your customer's own page has answered this since its calendar arrived, so the app now does the same thing, in the same look: a small dark bubble above the day names it (“Malaysia Day”), and it goes away as soon as you tap anywhere else."),
      el("p", { class: "hint" },
        "Nothing else about the tap changed: at Orders it still opens the day, on a product's Availability calendar it still marks or unmarks the sell day, on Delivery Dates it still starts the range you are about to mark. A day inside two marks takes the name of the shorter one — the same rule the colours already follow — and a day already gone is never named. Two kinds of day that could not be read at all can now: a marked day at Orders you do not post for, and a day on Delivery Dates that is already one of your posting dates. The Order date boxes name their day above the date rather than above a day of the month, because those boxes fold their calendar the moment a day is picked.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The marks on the Orders screen now sit on their days (Engine v86)"),
      el("p", { class: "card-sub" },
        "The days on the Orders screen are taller than the days anywhere else, because a posting day there carries its booking count under its number. That had two effects. A holiday band was stretched to fill its week row, so it came out deeper there — and deeper in the weeks holding a posting day than in the others — so one holiday's own band changed depth from row to row inside a month. And a plain day kept the app's usual height inside a taller row, so a single-day mark was drawn a few pixels higher on a day you do not post for than on a day you do. A band is now a sheet of one depth centred on its row, every day of that month is one height whether or not it is a posting day, and today on that screen glows around its number."),
      el("p", { class: "hint" },
        "Only the drawing changed. The shop's calendar and your Delivery Dates calendar look exactly as before — their days are all one height, so they never had this — and no mark was added, moved or removed.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Your marked days are drawn on every calendar in the app (Engine v85)"),
      el("p", { class: "card-sub" },
        "Until now a holiday only appeared on the customer's calendar and on the Delivery Dates screen you marked it on. Every other calendar drew a plain month: the month calendar at the top of Orders, the little Order date calendars in the new-order form and the Edit pop-up, the posting-day picker inside that pop-up, and a product's Availability calendar where you mark the days it sells. A holiday you were planning around was invisible on every screen you actually plan on. All of them now draw your marks, in the same two shapes and the same colours as the Delivery Dates calendar — a see-through band across a run, deeper the shorter the run, and a box for a single day."),
      el("p", { class: "hint" },
        "A mark on a day you do not post for is drawn too, on the dimmed day, since that is the only way a holiday on a quiet day can be seen at all. Two small pieces of the drawing were tidied while moving it: the green tint on a day a product sells is now a see-through wash rather than a flat fill, so a holiday band running behind it still shows through instead of vanishing on exactly the days you sell; and a marked day that happens to be today keeps today's soft glow.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A day you marked is one gentle wash everywhere (Engine v84)"),
      el("p", { class: "card-sub" },
        "A mark used to be drawn one of two ways, decided by a single question: is this a day you post for? On a day you post for, the mark went pale so the green “you can order” ring stayed the first thing the eye read; on a day you don't, it was a full-colour solid block with the number turned white. So the same kind of holiday could look like two different things — and a mark quietly changed its own appearance as the posting window moved towards it. A mark is now only ever a see-through wash of its own colour, and its depth follows how long the mark runs: a one-day holiday the deepest, a long school break the palest."),
      el("p", { class: "hint" },
        "The customer's calendar and your own Delivery Dates calendar read that depth from the same place, so a day wears exactly the same mark on both sides of the shop and in every month. Nothing is a solid block of colour any more, which also means the date number and the green posting pill always read on top of a mark, whether or not you post that day.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Marking a holiday now tells the shop straight away (Engine v83)"),
      el("p", { class: "card-sub" },
        "A day you mark on the Delivery Dates calendar is drawn on the customer's own calendar. But saving a mark only ever sent your posting days to the cloud — it never sent the customer's page anything — so the marks reached the shop only by accident, whenever you next happened to save a product or a setting. Mark the holiday, open the shop, and nothing had changed. Now the same save does both: marking a day, removing a mark, loading a set from the standard list, or renaming or recolouring one all republish the customer's page within a couple of seconds, exactly the way editing a product does."),
      el("p", { class: "hint" },
        "One tap to catch up the marks you already have: the fix sends the marks from now on, and the ones already on your calendar have never been sent at all, so open More → Settings → Storefront and tap Publish now once. After that the shop's calendar follows your marks by itself. Nothing else about a mark changed: it is still only ever something to see while planning, it still never adds or removes a posting day, and a name you typed yourself still never leaves your phone.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A product's selling days are marked on its own calendar (Engine v82)"),
      el("p", { class: "card-sub" },
        "Until today a product could say only two things about when: a notice period, and one from-date and to-date for a season. You asked to set it freely instead, so those two date boxes have become a card you mark — the Availability card, sitting under Daily limit and folded until you tap its title. Folded, its title tells you what is marked, so the Products list alone tells you a product's selling days: “Every day”, or “Sat & Sun”, or “1-24 Dec 2026”. Inside, it is a month calendar and four gestures: tap a weekday letter (M, T, W…) and every one of that weekday in the month shown is marked; tap one day to mark just that day; slide your finger across several days and the whole run is marked; and tapping or sliding over a day that is already marked takes it back."),
      el("p", { class: "hint" },
        "Nothing carries over into the next month — that is the point of it, so a December-only set stays December-only and January starts with nothing marked. A product whose card you have never opened sells on every posting day exactly as before, so nothing on your live shop moves until you mark it. A period that crosses a month or a year is one mark with two ends you can stretch, and a small x removes a mark whole. On the order page a day a product is not sold for is not a note — the product is simply not there; the one rule that keeps its note is the notice period, because that product IS sold that day, it only has to be ordered earlier. The old From/To boxes are gone, and a product that had them opens with that period already sitting in the card, so nothing you set before is lost.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A holiday you marked is drawn on the shop the way your own calendar draws it (Engine v81)"),
      el("p", { class: "card-sub" },
        "The marks were already reaching the shop; it was only their shape that differed, and a mark that looks different on the customer's page than on yours is a mark your customer has to learn twice. The shop had been drawing each marked day as its own flat pale square, so a holiday running over a week read as a row of separate blocks where your own calendar shows one continuous shape. A holiday running over several days is now one unbroken see-through band across them, deeper the shorter the run, and a single-day holiday is a solid box in its full colour, a touch narrower so a longer band still peeks out at its sides."),
      el("p", { class: "hint" },
        "The one place it gives way is a day you post for: green is the colour the posting ring uses and a solid box would swallow it, so the box goes pale there and the green ring stays the first thing the eye reads — the mark is still there, and the day is still named on a tap. Your own typed-in days still never reach the shop: only a day that is, by name and date, one of the built-in standard days can be published, so your own notes stay private to your phone.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Today glows, a holiday is a tint you can tap, and Orders leads with the same calendar (Engine v80)"),
      el("p", { class: "card-sub" },
        "Three small things, all pulling the same way: a calendar should read the same on both sides of the shop, and nothing drawn on it should look like something it is not. On the shop, today no longer wears a little red rectangle — it traced the day's number as a box on a day you do not post for — and is now a gentle glow that breathes around the number, sitting happily on a posting day too (the green ring says you can order for this day, the soft glow says it is today). A holiday you marked is a pale wash of its own colour over the whole day, deliberately neither a ring nor a dot, because a ring is what “you can order for this day” looks like; tap it — or on a computer, rest the mouse on it — and a small bubble names the day. And the Orders screen's sideways date strip is now the same month calendar the customer sees: posting days ringed in green with how booked it is under each (“3/12”, or FULL), a closed day's count in red, and a day already gone dimmed but still opening."),
      el("p", { class: "hint" },
        "The ＋ New order card now arrives folded and reads in the order you think in: the month calendar first, then the customer's details, then the items — it stays open after you add an order. The Edit pop-up's Delivery day calendar is simply there now rather than behind a button, and both pop-up and card read day, then details, then items. The “Holidays” line under the shop's grid is gone; the name comes out on a tap instead.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The customer picks a posting day on a calendar, and so do you in the app (Engine v79)"),
      el("p", { class: "card-sub" },
        "The shop used to show its posting days as a row of date chips laid out sideways. Under Pick a posting day the customer now sees a month calendar — one month at a time, with arrow buttons either side of the month's name to look ahead or back. The days you are taking orders for are picked out in green; every other day of the month is plain and cannot be tapped. They tap a green day and the day they chose is written out in words just underneath — “Your posting day: Wed, 16 Sep” — with a “Sold out: …” line when a day in the month is full. The first open day is already chosen for them when the page opens, so ordering can never be blocked by forgetting to tap."),
      el("p", { class: "hint" },
        "In the app the same little calendar now stands wherever you name a date. The Edit pop-up's Delivery day is no longer a drop-down: it names the order's current day and opens a calendar beneath it, with every day still to come tappable plus the order's own day even if it has passed. The Order date box is a calendar too, with a Today shortcut. And the ＋ New order card has gained a Delivery day picker at its top — tap another green day and the whole screen moves to it, so the product list you choose from is always the one that is actually sellable for the day you picked. Only the standard days you have marked reach the customer; a day you typed yourself stays private to your phone, and marking nothing leaves the shop's calendar carrying nothing.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The calendar's Add buttons now say what they do (Engine v78)"),
      el("p", { class: "card-sub" },
        "On the Delivery Dates screen, “Mark an occasion” carried a small button reading “＋ Add occasion”. That name didn't tell you it opens a ready-made list of Malaysia's holidays and fun days, all ticked and waiting — so you had to open it to find out. It now reads “＋ Load standard occasions”, and the window it opens is titled the same."),
      el("p", { class: "hint" },
        "Inside that window there were two buttons both called “Add” — the big one at the bottom that files the days you ticked, and a smaller one in the “My own day” strip just above it, which files a day you name yourself. Reaching for “Add” and hitting the wrong one gave you “Type a name first”, for a day you never meant to name. The smaller one is now spelled out as “Add my own day”, so the only plain Add in the window adds the days you ticked. Nothing else on that screen moved.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The translated-text card says what a blank line means (Engine v77)"),
      el("p", { class: "card-sub" },
        "A wording fix on top of v76's fold-away card. The greyed line in a product's translated-text card used to end “blank keeps English”; it now finishes “if blank, it will be filled with English” — stating what the customer gets, rather than what the line does. The card's own sub-line ends the same way."),
      el("p", { class: "hint" },
        "The rule underneath is unchanged: delete what is in a line and the greyed suggestion and its arrow come back exactly as before, → still takes the words, and ↻ still re-translates that one line.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The translated text folds away, filled a line at a time (Engine v76)"),
      el("p", { class: "card-sub" },
        "The translated-text corner of a product was the busiest part of the screen: always open, eight lines each with its own “Translate this one” button, two “Fill all” buttons above, and an “auto” tag to decode. It is now one quiet card that starts shut and stays shut — it's setup, not daily use. Tap the title to open it, tap anywhere outside to fold it back. Opened, each empty line shows its translation already worked out as the app's standard greyed suggestion with the → at its right edge — the same gesture as every other suggested box — and taking it swaps the arrow for a ↻ that re-translates just that line. Typing your own words hides the ↻ (the line is yours); a blank line keeps the English."),
      el("p", { class: "hint" },
        "A product you never open the card for still reads in all three languages on the shop — the auto-translate still runs after every save and publish.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The green glow on a jumped-to order waits for you (Engine v75)"),
      el("p", { class: "card-sub" },
        "Tapping a row in the New Orders inbox (or a result in Find an order) takes you to that order's posting day and lights the order up green — but the glow faded after under two seconds, which is no time at all while your eye is still travelling down a long day, and you were left hunting for a row that was no longer lit. The glow now keeps pulsing until your finger arrives on the row, and stops the moment you reach it."),
      el("p", { class: "hint" },
        "If your phone is set to reduce motion, the green ring holds steady instead of pulsing — it still stays until you reach the row.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The little arrow in an empty box keeps working (Engine v74)"),
      el("p", { class: "card-sub" },
        "Engine v73 added the small right-arrow at the right edge of a box showing a greyed example: press → on a keyboard, or tap the arrow, and the example drops in as real text. On a phone the tap worked the first time and then stopped — once you had tapped into any box, tapping the arrow on the next one did nothing, because taking a suggestion opened the phone's keyboard, which shrank and shifted the page under your thumb. Taking a suggestion no longer opens the keyboard, the strip that counts the tap is about half again as wide, and the tap is judged against the box's own edge as well as its place on the page — so a thumb landing a little wide still counts."),
      el("p", { class: "hint" },
        "The drawn arrow is kept exactly as it was — same size, same place — and a tap on the greyed example itself is still an ordinary tap that puts the cursor there.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Change windows, moving an order, your Policies, and a one-tap suggestion (Engine v73)"),
      el("p", { class: "card-sub" },
        "Four things. Each product can now carry a “Changes or cancellations (days before delivery)” box: the customer reads the sentence on the product's card and again on their green “Order received!” card, and a mixed basket shows the strictest (largest) figure. Blank means no window is stated and 0 states no advance limit — neither ever blocks you, who move every order by hand. An order's posting day can now be changed in the app instead of deleted and re-typed (a deletion reads as a cancellation): the Edit-order pop-up gains a “Delivery day” select of every day still to come, and saving moves the whole order across, warning softly if the new day falls inside the customer's window. A Policies box in Settings → Storefront holds your own cancellation and refund wording — typed once in English, translated to Chinese and Bahasa Malaysia, and drawn on the shop under Track your order in the visitor's language, with the line breaks you typed. Blank hides the section."),
      el("p", { class: "hint" },
        "And app-wide, where an empty box shows the app's greyed recommendation, the right arrow — or a tap on the small arrow drawn at the box's right edge — accepts it as real text, like an AI chat prompt. Your Supabase email, key and password boxes and the sign-in fields carry no arrow, so a made-up login can never be accepted by accident.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Sold-out notes read in the customer's language (Engine v72)"),
      el("p", { class: "card-sub" },
        "Two corners of your order page used to stay English whichever language a customer picked: the small note on a product that can't be ordered for the posting day they chose (that it only opens from a date, only runs up to one, or that orders close so many days ahead), and the notes that appear above the menu when the page had to change their basket — something that just sold out, or a quantity trimmed to what is left."),
      el("p", { class: "hint" },
        "Both now read in English / 中文 / BM with everything else, and the date in the note is written in their language too — so nothing English can slip into a Chinese or Malay page. An English visit reads exactly as it did.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "The order page's language buttons answer instantly (Engine v71)"),
      el("p", { class: "card-sub" },
        "Tapping English / 中文 / BM on your order page used to reload the whole page — re-downloading the menu, the “only N left” numbers and your saved order-page settings, which is a pause on a phone. It now switches in place, like your homepage already did: the words change the instant they tap and nothing is downloaded again."),
      el("p", { class: "hint" },
        "Anything the customer had already done is left untouched — their basket, the posting day they chose, and the name, WhatsApp number and address they typed. If they were looking up an order, that card re-reads in the new language too.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "An order keeps the name and price it was sold at (Engine v70)"),
      el("p", { class: "card-sub" },
        "An order now remembers what it was sold as and what it was sold for, frozen the moment you take it — from the shop or typed in by hand. Rename a product or change its price later and your past orders, the labels, customer spend and the tracking page a customer sees all stay on the old name and price. A product you delete afterwards still shows what it was that someone bought."),
      el("p", { class: "hint" },
        "Deliberately swapping a line to a different product when you edit an order picks up the new price — you changed what is being sold. A line you leave alone keeps the price it was sold at. Orders from before today are stamped once with what they were already showing.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Either place updates the customer (Engine v69)"),
      el("p", { class: "card-sub" },
        "A customer's name and number now follow whichever you edited last. Fix a name with “Edit” on one of their orders and that is the one the list, the history pop-up and the “Hi {name}!” greeting use; open their card, type the name and save, and the card's name is used instead. Neither place is the boss — and because each save writes through to the other, they normally read the same anyway. This only decides the rare case where an old copy and a newer one both sit there."),
      el("p", { class: "hint" },
        "Nothing to set up — your phones pick it up with the next sync.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "One name and one number per customer (Engine v68)"),
      el("p", { class: "card-sub" },
        "A customer's name and WhatsApp number used to live in two places — on their orders and on their customer card — and could disagree. Now saving the card writes the name and number onto every one of their orders, so your labels, messages and customer list all follow; and fixing a wrong number with “Edit” on an order carries back to their card too. Leaving a box empty means “leave it as it is” — it never wipes a number your confirmations need. Anyone you renamed before today gets put right automatically the first time this version opens."),
      el("p", { class: "hint" },
        "Correcting a number brings that customer's bring-a-friend credits across with it, and renaming someone with no number on file no longer loses them.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A “No name” customer keeps the name you save (Engine v67)"),
      el("p", { class: "card-sub" },
        "When a customer reaches you without a name — a storefront order that carried none — their row in the customer book now takes the name you save on their profile. Open the person, tap “Add details”, type their name (and the pet's name, likes and so on) and save: the row, the finder and the “Hi {name}!” WhatsApp greeting all use it from then on. Before, the row only ever read the order, so an unnamed customer stayed “No name” no matter what you typed."),
      el("p", { class: "hint" },
        "Your order's own name still wins when there is one — the saved profile name only fills in for someone recorded anonymously.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Product text that translates itself into 中文 & Bahasa Malaysia (Engine v66)"),
      el("p", { class: "card-sub" },
        "When you save or publish a product, the app quietly fills the Chinese and Malay versions of its name, description, selling unit and feeding tip — machine-made from your English, free, whenever you're online. Each translated box is tagged “auto”. Type over any box and it becomes yours: your own wording is never overwritten. In Products → Edit you can also tap “Fill all 中文” or “Fill all Bahasa Malaysia”, or fill one line at a time with ↻. Blank English means no translation, and if you later change an English line, that box is re-filled to match."),
      el("p", { class: "hint" },
        "A shopper reading in that language then sees the product in their own words on your order page — a translation only ever exists because your English version does.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Products in three states: Draft, On the shop, Hidden (Engine v66)"),
      el("p", { class: "card-sub" },
        "Products now sit in three separate lists. A brand-new product starts as a Draft — fully built but not for sale until you Publish it. On the shop holds what customers can actually order. Hidden is a product you took down but want to keep (history and recipe stay). Publish a draft to start selling it; Hide any live product to pause it."),
      el("p", { class: "hint" },
        "Drafts and Hidden products never appear on your storefront and can't be ordered, so building a new recipe can't accidentally go live.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Copy the referral follow-up in your customer's language (Engine v66)"),
      el("p", { class: "card-sub" },
        "In a customer's profile, before you tap “🎉 Copy follow-up”, you can pick the message's language — English, 中文 or Bahasa Malaysia. The whole check-in, including the product's translated name and feeding tip, is written in that language, so the text you paste into WhatsApp already speaks in your customer's own words. English stays the default."),
      el("p", { class: "hint" },
        "The follow-up is the warm check-in that slides the bring-a-friend link in after a delivery.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Reviews to publish, one at a time (Engine v65)"),
      el("p", { class: "card-sub" },
        "More → Reviews now shows each review one at a time, exactly as it will look on your homepage — the ones waiting to be published first. Publish puts it up, Take down hides it, Delete removes it for good, and each action moves you on to the next one. Home and the ⭐ Reviews menu row show an “N waiting” count whenever new reviews are sitting on you."),
      el("p", { class: "hint" },
        "No autoplay on purpose: it's a deciding screen, not a slideshow — the review in front of you stays until you act on it.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "中文 / English / Bahasa Malaysia — the whole site (Engine v64)"),
      el("p", { class: "card-sub" },
        "Your homepage and ordering page now speak three languages. Tap English / 中文 / BM at the top and every word — buttons, delivery days, the order form — switches over on the spot (your phone remembers the choice). You can also give a product a Chinese or Malay shop name in Products, so the card reads 鸡肉干 or Jerky Ayam while orders still track the English name."),
      el("p", { class: "hint" },
        "Each visitor picks their own language, so one link works for every customer.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Homepage reviews as a carousel + a website credit (Engine v64)"),
      el("p", { class: "card-sub" },
        "The “What customers say” section on your homepage now swipes — readers drag left or right through the reviews you've published, or tap the dots. And if your website was made for you, Settings → Website & developer lets you name who built it: a small “Website by …” credit then shows at the bottom of the homepage and order page, and More → About gains a WhatsApp and email row to reach them."),
      el("p", { class: "hint" },
        "The same developer is who the wish list emails. Add a wish on More and it can send the whole list to them automatically — or tap “✉ Email the full list” to send it yourself.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A Customers tab with profiles & a finder (Engine v63)"),
      el("p", { class: "card-sub" },
        "Customers now has its own tab in the bottom bar, and each person can carry a small profile — their pet's name, a photo, what they like, what to avoid, and a note. Type in the finder box to narrow the list by name, number, pet's name or favourite product. Dogs and cats both fit. The Purchase Order screen moved under More to make room, and photos you pick are shrunk to a tiny thumb before saving."),
      el("p", { class: "hint" },
        "Profiles ride the same customer list on both your phones, so what you learn about a regular on one phone is there on the other.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "An always-on Upcoming holidays card (Engine v63)"),
      el("p", { class: "card-sub" },
        "On Home, the “Upcoming holidays” card now always shows: with nothing marked it explains how to add days on the Delivery calendar, and once more than three are coming up the list scrolls instead of dropping the rest."),
      el("p", { class: "hint" },
        "Before, a quiet week made the card vanish — now it's a steady reminder either way.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Engine version, wish list & change history (Engine v63)"),
      el("p", { class: "card-sub" },
        "More now shows which engine version you're on, has a wish list where you can jot ideas for the app (a tick stays ticked until you untoggle it), and links to the full change history from v54 onwards as a PDF you can read on any phone."),
      el("p", { class: "hint" },
        "Think of the wish list as your idea notebook for the software, kept with the app itself.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Amber “not sharing” strip + read-only backup View (Engine v62)"),
      el("p", { class: "card-sub" },
        "When a phone isn't on the shared cloud — shared data off, never set up, or signed out — an amber strip now shows on every screen so you always know. And each copy under Settings → Backup & safety has a View button: it opens that copy read-only (its orders, prices and stock), so you can check an old detail without moving today's data."),
      el("p", { class: "hint" },
        "Viewing a backup changes nothing — no writes, no reload — it's a window into that copy's past.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Cloud backups you can step back to (Engine v61)"),
      el("p", { class: "card-sub" },
        "Every day you open the app signed in, a full copy of your records quietly saves to your own cloud — a Daily copy the first time the app opens each day, a Weekly copy on Mondays, a Monthly copy on the 1st. It keeps the newest 7 daily, 4 weekly and 3 monthly copies. In Settings → Backup & safety you can Restore your phone back to any copy (a “Before restore” copy is saved first, so you can undo it), Download one as a file, or Delete it. Automatic copies tidy themselves up; Manual ones stay until you delete them."),
      el("p", { class: "hint" },
        "Your cloud copies sit behind the same private login as your shared records — customers never see them. Restore rewinds your phone AND the shared cloud to that copy.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Homepage reviews you approve first (Engine v60)"),
      el("p", { class: "card-sub" },
        "Your homepage can now show a “What customers say” section. Visitors leave a review — a star rating, a few words in English / 中文 / Bahasa Malaysia, and an optional photo — but nothing appears publicly until YOU tap Publish on it, in More → Reviews. New ones sit under Waiting for you; Publish puts it on the homepage, Take down hides it again, Delete removes it for good."),
      el("p", { class: "hint" },
        "Customers post into your own cloud and only your tap makes it public — the same trust step as confirming a storefront order before accepting it.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "Tick a whole occasion group at once (Engine v59)"),
      el("p", { class: "card-sub" },
        "On the Delivery calendar → Mark an occasion, the import list groups the ready-made occasions — pet days, people & kindness days, and more — so you can tick a whole group in one tap, then untick any you don't want before adding them all to your calendar. A “My own day” box lets you type any occasion the list doesn't have, e.g. “Pet-treat promo day”."),
      el("p", { class: "hint" },
        "Whole-group ticking saves taps when you want most of a group; the group's master checkbox shows a dash when only some of its days are ticked.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A catalogue of occasions to add (Engine v58)"),
      el("p", { class: "card-sub" },
        "Behind “＋ Add occasion” on the calendar is now a curated list of ready-made special days — Malaysian public holidays plus fun days for pets and people (World Animal Day, National Pet Day, International Cat & Dog Day and similar) — colour-coded red for public holidays, orange for the rest, so the calendar stays easy to read."),
      el("p", { class: "hint" },
        "These are suggestions to import, never automatic — you choose which ones land on your calendar.")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "A note on each ingredient line (Engine v57)"),
      el("p", { class: "card-sub" },
        "In a product's recipe, every ingredient line can now carry its own short note about that ingredient for this product only — e.g. which cut or brand of chicken, or which variety of sweet potato. It's for your eyes alone: it never appears on the shop, a label, or the product cards. Because it rides on the product like the recipe does, both your phones see it."),
      el("p", { class: "hint" },
        "Sits under the “amount × price” line — the same ingredient can read differently in different products (e.g. chicken in one recipe, duck in another).")),
    el("div", { class: "card" },
      el("p", { class: "card-title" }, "“Keep at least” reserve stock (Engine v56)"),
      el("p", { class: "card-sub" },
        "On the Ingredients screen, next to “On hand” there's now “Keep at least”. That's your floor — how much you want left on the shelf after a busy posting day. Your shopping list tops an ingredient back up to that level automatically, so you're never caught short. Set it once per ingredient; it syncs with the ingredient, so both your phones see the same number."),
      el("p", { class: "hint" },
        "Runs on top of the “On hand” stock number (Engine v54) — if you track what you have, the app can tell you what to re-buy.")));
}

function introCard() {
  return el("div", { class: "card" },
    el("p", { class: "card-title" }, "Your app, explained"),
    el("p", { class: "card-sub" },
      "Your bakery app and this app are twins under the hood — they share the same engine. This guide explains the engine in everyday words, so the two never feel confusing."),
    el("p", { class: "card-sub" },
      "It lives only here in Munchies Furkidz — your bakery app doesn't need it."));
}

function analogyRows(rows) {
  return rows.map(([term, meaning, analogy]) =>
    el("div", { class: "card" },
      el("p", { class: "card-title" }, term),
      el("p", { class: "card-sub" }, meaning),
      el("p", { class: "hint" }, "Analogy: " + analogy)));
}
